/**
 * PPM Compass 360 - Realistic Multi-Department Dataset for Small & Mid-Sized Enterprises (SMEs)
 * Featuring Multi-Department PPM Implementation (80% progressed), Cloud ERP, Warehouse Automation, and Operations.
 */

window.PPM_DEMO_DATA = {
  "portfolios": [
    {
      "id": "all",
      "name": "All Portfolios"
    },
    {
      "id": "enterprise",
      "name": "IT Systems & Infrastructure"
    },
    {
      "id": "operations",
      "name": "Operations & Supply Chain"
    },
    {
      "id": "engineering",
      "name": "Engineering & Product Design"
    },
    {
      "id": "digital",
      "name": "Customer Solutions & Digital"
    },
    {
      "id": "facilities",
      "name": "Facilities & Real Estate"
    },
    {
      "id": "finance",
      "name": "Finance & Corporate Services"
    }
  ],
  "projects": [
    {
      "id": 1,
      "code": "PPM-101",
      "title": "PPM Compass 360 Multi-Department Implementation",
      "portfolio": "enterprise",
      "portfolioName": "IT Systems & Infrastructure",
      "type": "Software Implementation & Governance",
      "phase": "Execution",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Sarah Jenkins",
      "leadEmail": "s.jenkins@contoso.com",
      "deputy": "Devon Clark",
      "sponsor": "Executive Steering Committee (IT, Operations & Engineering Directors)",
      "erpCode": "PPM-2026-GOV",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Yellow",
      "ragScope": "Green",
      "ragReason": "Department 1 (IT) and Department 2 (Operations) fully live with positive user feedback; Department 3 (Engineering & R&D) rollout at 80% with final team coaching and backlog migration underway.",
      "percentComplete": 80,
      "startDate": "2026-03-01",
      "targetDate": "2026-10-31",
      "description": "Evaluating and implementing PPM Compass 360 across 3 key operating departments (IT & Cloud Infrastructure, Operations & Logistics, and Engineering) to eliminate fragmented Excel workbooks and unify project portfolio governance inside Microsoft 365.",
      "goal": "Unify project tracking across IT, Operations, and Engineering inside Microsoft 365, eliminating disjointed Excel sheets and delivering real-time executive visibility with 100% in-tenant data residency.",
      "scope": "Tenant SPFx app catalog deployment, metadata taxonomy standardization for 3 department portfolios, role-based SharePoint list permissions, legacy spreadsheet data migration, executive RAG rollup configuration, and training for 45 project leaders and portfolio owners.",
      "successMeasures": "80% project completion reached across all 3 departmental portfolios; 100% elimination of manual weekend status compilation; 100% Microsoft 365 security & compliance conformance.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/PPM-101",
      "mppUrl": "https://contoso.sharepoint.com/sites/PMO/Plans/PPM-Compass-3-Dept-Rollout.mpp",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PPM-Compass-Rollout",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 2,
      "code": "ERP-102",
      "title": "Cloud ERP Migration & Warehouse Inventory Sync",
      "portfolio": "enterprise",
      "portfolioName": "IT Systems & Infrastructure",
      "type": "Business Systems",
      "phase": "Execution",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "David Vance",
      "leadEmail": "d.vance@contoso.com",
      "deputy": "Elena Garcia",
      "sponsor": "Michael Chang (COO & Head of Operations)",
      "erpCode": "ERP-2026-02",
      "ragOverall": "Yellow",
      "ragTimeline": "Yellow",
      "ragBudget": "Yellow",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Integration testing with regional warehouse identified 2 barcode scanning interface delays; supplier patch scheduled for testing next week.",
      "percentComplete": 78,
      "startDate": "2025-10-01",
      "targetDate": "2026-11-15",
      "description": "Transition of legacy on-premise accounting and inventory database to cloud ERP, linking purchasing, sales orders, and regional warehouse dispatch.",
      "goal": "Eliminate manual double-entry of packing slips and provide unified inventory counts across branches.",
      "scope": "Core general ledger, accounts payable/receivable, warehouse stock sync, and role-based branch manager dashboards.",
      "successMeasures": "99.5% inventory ledger reconciliation accuracy, zero lost orders during cutover, and automated invoice delivery.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/ERP-102",
      "mppUrl": "https://contoso.sharepoint.com/sites/PMO/Plans/ERP-Cloud-Migration.mpp",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/ERP-Migration",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 3,
      "code": "CRM-103",
      "title": "B2B Customer Portal & Self-Service Order Tracking",
      "portfolio": "digital",
      "portfolioName": "Customer Solutions & Digital",
      "type": "Customer Experience",
      "phase": "Execution",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Amara Diallo",
      "leadEmail": "a.diallo@contoso.com",
      "deputy": "Liam O'Connor",
      "sponsor": "Jessica Miller (Commercial Director)",
      "erpCode": "CRM-9801",
      "ragOverall": "Red",
      "ragTimeline": "Red",
      "ragBudget": "Yellow",
      "ragResources": "Red",
      "ragScope": "Green",
      "ragReason": "Customer single sign-on (SSO) SAML identity integration with legacy client directory delayed by 3 weeks; external contractor assigned to assist.",
      "percentComplete": 54,
      "startDate": "2026-02-01",
      "targetDate": "2026-10-31",
      "description": "Secure web portal enabling B2B commercial clients to review real-time order fulfillment status, download invoices, and request re-orders.",
      "goal": "Reduce routine inbound customer inquiry calls by 40% while accelerating order repeat rate.",
      "scope": "Customer authentication portal, ERP order lookup API, PDF invoice retrieval, and email tracking notifications.",
      "successMeasures": "Sub-1 second catalog search, 40% reduction in status calls to sales reps, and positive feedback from top 20 clients.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/CRM-103",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/B2B-Portal",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 4,
      "code": "CYB-104",
      "title": "M365 Zero-Trust Security & ISO 27001 Baseline",
      "portfolio": "enterprise",
      "portfolioName": "IT Systems & Infrastructure",
      "type": "Cybersecurity & Compliance",
      "phase": "Testing",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Rachel Wu",
      "leadEmail": "r.wu@contoso.com",
      "deputy": "Alexander Wright",
      "sponsor": "David Vance (VP Technology & Risk)",
      "erpCode": "SEC-4412",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Phishing simulation and endpoint protection rollout completed on all 280 staff workstations ahead of schedule.",
      "percentComplete": 88,
      "startDate": "2026-01-10",
      "targetDate": "2026-09-30",
      "description": "Implementation of Microsoft Defender for Endpoint, Intune MDM compliance policies, conditional access MFA, and SharePoint sensitivity classification.",
      "goal": "Achieve comprehensive cyber resilience and satisfy vendor security questionnaire requirements for enterprise clients.",
      "scope": "Intune deployment, conditional access policy enforcement, BitLocker disk encryption, and automated phishing training.",
      "successMeasures": "100% staff compliance on hardware MFA, zero critical vulnerability findings in external penetration test.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/CYB-104",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/Cyber-ZeroTrust",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 5,
      "code": "OPS-201",
      "title": "Warehouse Barcode Scanning & Pick-and-Pack Automation",
      "portfolio": "operations",
      "portfolioName": "Operations & Supply Chain",
      "type": "Supply Chain",
      "phase": "Execution",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Devon Clark",
      "leadEmail": "d.clark@contoso.com",
      "deputy": "Henrik Lindqvist",
      "sponsor": "Marcus Brody (Director of Supply Chain)",
      "erpCode": "OPS-5501",
      "ragOverall": "Yellow",
      "ragTimeline": "Yellow",
      "ragBudget": "Green",
      "ragResources": "Yellow",
      "ragScope": "Green",
      "ragReason": "Zebra wireless hand scanners shipment arrived 10 days late; floor staff staging sessions compressed into evening shifts.",
      "percentComplete": 62,
      "startDate": "2026-03-15",
      "targetDate": "2026-11-15",
      "description": "Deployment of ruggedized handheld barcode scanners and thermal label printers integrated directly with cloud inventory stock records.",
      "goal": "Cut order picking errors by 70% and eliminate paper-based warehouse manifest sheets.",
      "scope": "45 handheld mobile scanners, warehouse Wi-Fi mesh expansion, pallet barcoding, and picker verification workflows.",
      "successMeasures": "Pick error rate under 0.1%, pick-to-pack throughput increased by 28% across 2 warehouse zones.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/OPS-201",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/Warehouse-Automation",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 6,
      "code": "LOG-202",
      "title": "Regional Delivery Fleet GPS Routing & Telematics",
      "portfolio": "operations",
      "portfolioName": "Operations & Supply Chain",
      "type": "Logistics & Fleet",
      "phase": "Execution",
      "priority": "Medium",
      "overallStatus": "Running",
      "lead": "Liam O'Connor",
      "leadEmail": "l.oconnor@contoso.com",
      "deputy": "Marcus Brody",
      "sponsor": "Marcus Brody (Director of Supply Chain)",
      "erpCode": "FLEET-620",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Hardware telemetry dongles installed across first 18 delivery vans; route optimization software showing 14% fuel savings in pilot.",
      "percentComplete": 45,
      "startDate": "2026-04-01",
      "targetDate": "2026-12-15",
      "description": "Installation of OBD-II GPS telematics across commercial delivery fleet with dynamic route planning and electronic delivery signatures.",
      "goal": "Optimize daily delivery drops, reduce fleet fuel expenditure, and provide customers with accurate delivery ETA alerts.",
      "scope": "28 commercial vans, GPS tracking hardware, mobile electronic proof-of-delivery (ePOD) app, and dispatch dashboard.",
      "successMeasures": "15% average route fuel reduction, on-time delivery rate exceeding 96%.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/LOG-202",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/Fleet-Telematics",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 7,
      "code": "FAC-301",
      "title": "Central Distribution Center Office & Mezzanine Expansion",
      "portfolio": "facilities",
      "portfolioName": "Facilities & Real Estate",
      "type": "Facility & Infrastructure",
      "phase": "Closeout",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Sarah Jenkins",
      "leadEmail": "s.jenkins@contoso.com",
      "deputy": "Elena Garcia",
      "sponsor": "Michael Chang (COO & Head of Operations)",
      "erpCode": "FAC-9011",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Final building inspector signoff and municipal occupancy permit received; snagging punch-list 95% cleared.",
      "percentComplete": 92,
      "startDate": "2025-11-01",
      "targetDate": "2026-09-30",
      "description": "Construction of 4,000 sq ft structural steel mezzanine, 8 operational supervisor workstations, breakroom, and low-voltage network cabling.",
      "goal": "Expand logistics administrative footprint without requiring an expensive secondary warehouse lease.",
      "scope": "Mezzanine engineering, HVAC ducting extension, Cat6A network drops, LED lighting, and ergonomic furniture installation.",
      "successMeasures": "Zero lost-time safety incidents during construction, completed within 2% of approved contingency budget.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/FAC-301",
      "mppUrl": "https://contoso.sharepoint.com/sites/PMO/Plans/Mezzanine-Expansion.mpp",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/Facility-Expansion",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 8,
      "code": "ENG-401",
      "title": "Next-Gen Compact Sensor Hardware Prototyping",
      "portfolio": "engineering",
      "portfolioName": "Engineering & Product Design",
      "type": "R&D & Product Engineering",
      "phase": "Execution",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Henrik Lindqvist",
      "leadEmail": "h.lindqvist@contoso.com",
      "deputy": "Priya Patel",
      "sponsor": "Dr. Aris Thorne (VP of Product Engineering)",
      "erpCode": "ENG-202",
      "ragOverall": "Yellow",
      "ragTimeline": "Yellow",
      "ragBudget": "Green",
      "ragResources": "Yellow",
      "ragScope": "Green",
      "ragReason": "Custom microcontroller PCB rev 2.1 required trace impedance adjustments; environmental chamber testing delayed by 12 business days.",
      "percentComplete": 65,
      "startDate": "2026-01-15",
      "targetDate": "2026-11-30",
      "description": "Design, firmware engineering, and laboratory stress validation for new low-power industrial telemetry sensor line.",
      "goal": "Deliver battery-operated sensor with 5-year operating lifespan and Bluetooth LE / LoRaWAN wireless telemetry.",
      "scope": "Schematic design, 4-layer PCB layout, embedded C firmware, IP67 waterproof enclosure tooling, and CE/FCC pre-scan.",
      "successMeasures": "Current draw under 12uA in sleep mode, radio range over 800 meters, successful CE compliance testing.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/ENG-401",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/Sensor-Prototyping",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 9,
      "code": "FIN-501",
      "title": "Automated Accounts Payable & Invoice OCR Scanning",
      "portfolio": "finance",
      "portfolioName": "Finance & Corporate Services",
      "type": "Finance Process Automation",
      "phase": "Testing",
      "priority": "Medium",
      "overallStatus": "Running",
      "lead": "Elena Garcia",
      "leadEmail": "e.garcia@contoso.com",
      "deputy": "David Vance",
      "sponsor": "Elena Rostova (Finance Director)",
      "erpCode": "FIN-310",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "UAT phase completed with 120 live supplier invoices; OCR recognition rate achieved 94.2% automated matching accuracy.",
      "percentComplete": 82,
      "startDate": "2026-03-01",
      "targetDate": "2026-10-15",
      "description": "Integration of AI optical character recognition (OCR) and Power Automate workflows for automated invoice intake, line-item extraction, and approval routing.",
      "goal": "Accelerate supplier invoice approval from 7 days to 24 hours and capture early payment discounts.",
      "scope": "AI Builder document model training, Power Automate approval flows, ERP Accounts Payable ledger sync, and audit logging.",
      "successMeasures": "85%+ zero-touch invoice processing, reduction of invoice entry labor by 20 hours per week.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/FIN-501",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/AP-Automation",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 10,
      "code": "HR-601",
      "title": "Digital Time & Attendance Mobile Clock-In System",
      "portfolio": "operations",
      "portfolioName": "Operations & Supply Chain",
      "type": "HR & Workforce Operations",
      "phase": "Execution",
      "priority": "Medium",
      "overallStatus": "Running",
      "lead": "Priya Patel",
      "leadEmail": "p.patel@contoso.com",
      "deputy": "Sarah Jenkins",
      "sponsor": "Jessica Miller (VP People & Operations)",
      "erpCode": "HR-882",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Mobile clock-in pilot running smoothly across 60 shift employees at main distribution depot with 99% check-in compliance.",
      "percentComplete": 58,
      "startDate": "2026-04-15",
      "targetDate": "2026-11-30",
      "description": "Retirement of old wall-mounted punch cards in favor of a smartphone app with geofenced clock-in, shift trading, and payroll integration.",
      "goal": "Eliminate manual timesheet calculation errors and prevent punch buddy discrepancies across all warehouse shifts.",
      "scope": "Mobile app rollout, geofencing perimeters for 3 facilities, biometric face confirmation, and automated payroll export.",
      "successMeasures": "Payroll preparation time slashed from 3 days to 4 hours, 100% accurate shift overtime tracking.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/HR-601",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/HR-TimeTracking",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 11,
      "code": "QUA-701",
      "title": "ISO 9001:2015 Annual Quality Audit & Process Certification",
      "portfolio": "engineering",
      "portfolioName": "Engineering & Product Design",
      "type": "Quality & Governance",
      "phase": "Execution",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Alexander Wright",
      "leadEmail": "a.wright@contoso.com",
      "deputy": "Henrik Lindqvist",
      "sponsor": "Dr. Aris Thorne (VP Product & Quality)",
      "erpCode": "QUA-900",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Internal audits completed across all 6 departments with minor non-conformances resolved; ready for external registrar stage 1 review.",
      "percentComplete": 75,
      "startDate": "2026-02-01",
      "targetDate": "2026-10-31",
      "description": "Comprehensive quality management system (QMS) audit, standard operating procedure (SOP) revision in SharePoint, and accredited ISO recertification.",
      "goal": "Maintain accredited ISO 9001 certification required for key tier-1 supplier contracts and industrial procurement.",
      "scope": "Internal process audits, SharePoint document control library overhaul, management review meetings, and registrar audit accompaniment.",
      "successMeasures": "Recertification achieved with zero major non-conformances, 100% SOPs verified in version-controlled SharePoint library.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/QUA-701",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/ISO-Quality",
      "lastStatusUpdate": "2026-08-31"
    }
  ],
  "milestones": [
    {
      "id": 101,
      "projectId": 1,
      "milestoneId": "MS-01",
      "title": "Department 1 (IT Infrastructure) Pilot Evaluation & Go-Live",
      "phase": "Design",
      "eventType": "Go-Live",
      "isPhaseGate": false,
      "baselineDate": "2026-04-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-04-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-04-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 102,
      "projectId": 1,
      "milestoneId": "MS-02",
      "title": "Phase Gate 1: Multi-Department Steering Committee Governance Approval",
      "phase": "Design",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-05-10",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-05-10",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-05-09",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 103,
      "projectId": 1,
      "milestoneId": "MS-03",
      "title": "Department 2 (Operations & Supply Chain) Portfolio Configuration & Cutover",
      "phase": "Execution",
      "eventType": "Go-Live",
      "isPhaseGate": false,
      "baselineDate": "2026-06-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-06-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-06-28",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 104,
      "projectId": 1,
      "milestoneId": "MS-04",
      "title": "Phase Gate 2: M365 In-Tenant Security & Compliance Verification",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-07-20",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-07-20",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-07-18",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 105,
      "projectId": 1,
      "milestoneId": "MS-05",
      "title": "Department 3 (Engineering & R&D) Pilot User Training & Backlog Migration",
      "phase": "Execution",
      "eventType": "Testing",
      "isPhaseGate": false,
      "baselineDate": "2026-09-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 106,
      "projectId": 1,
      "milestoneId": "MS-06",
      "title": "Phase Gate 3: Final 3-Department Executive Sign-Off & Transition to BAU",
      "phase": "Closing",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-10-25",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-25",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    },
    {
      "id": 201,
      "projectId": 2,
      "milestoneId": "MS-01",
      "title": "Phase Gate 1: Chart of Accounts & General Ledger Structure Approved",
      "phase": "Planning",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2025-12-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2025-12-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2025-12-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 202,
      "projectId": 2,
      "milestoneId": "MS-02",
      "title": "Master Supplier & Customer Data Migration Validated",
      "phase": "Execution",
      "eventType": "Milestone",
      "isPhaseGate": false,
      "baselineDate": "2026-04-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-04-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-05-02",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 203,
      "projectId": 2,
      "milestoneId": "MS-03",
      "title": "Warehouse Barcode Scanning & Real-Time Stock Feed Integration Test",
      "phase": "Execution",
      "eventType": "Testing",
      "isPhaseGate": false,
      "baselineDate": "2026-08-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-10",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 204,
      "projectId": 2,
      "milestoneId": "MS-04",
      "title": "Phase Gate 2: Pre-Go-Live Operational Readiness Review",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-10-01",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    },
    {
      "id": 301,
      "projectId": 3,
      "milestoneId": "MS-01",
      "title": "Customer Persona Wireframes & UI Prototypes Approved",
      "phase": "Planning",
      "eventType": "Sign-off",
      "isPhaseGate": false,
      "baselineDate": "2026-03-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-29",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 302,
      "projectId": 3,
      "milestoneId": "MS-02",
      "title": "Customer SSO & Identity SAML Gateway Integration",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-07-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-05",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Late / Delayed",
      "showOnTimeline": true
    },
    {
      "id": 303,
      "projectId": 3,
      "milestoneId": "MS-03",
      "title": "Phase Gate 2: Client Advisory Council Beta Sign-off",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-09-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-10",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 401,
      "projectId": 4,
      "milestoneId": "MS-01",
      "title": "Phase Gate 1: Conditional Access Security Policy Baselines Approved",
      "phase": "Planning",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-03-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-12",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 402,
      "projectId": 4,
      "milestoneId": "MS-02",
      "title": "Intune Endpoint Protection & Disk Encryption on 280 Laptops",
      "phase": "Execution",
      "eventType": "Rollout",
      "isPhaseGate": false,
      "baselineDate": "2026-06-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-06-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-06-25",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 403,
      "projectId": 4,
      "milestoneId": "MS-03",
      "title": "Phase Gate 2: Third-Party External Penetration Test & Audit Sign-Off",
      "phase": "Testing",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-09-20",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-20",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 501,
      "projectId": 5,
      "milestoneId": "MS-01",
      "title": "Warehouse Industrial Wi-Fi Mesh Coverage Verification",
      "phase": "Planning",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-05-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-05-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-05-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 502,
      "projectId": 5,
      "milestoneId": "MS-02",
      "title": "45 Handheld Scanner Staging & Firmware Provisioning",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-07-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-08-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-08-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 503,
      "projectId": 5,
      "milestoneId": "MS-03",
      "title": "Shift Picker Training & Batch Scanning Verification",
      "phase": "Execution",
      "eventType": "Training",
      "isPhaseGate": false,
      "baselineDate": "2026-09-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 504,
      "projectId": 5,
      "milestoneId": "MS-04",
      "title": "Phase Gate 2: Full Warehouse Paperless Manifest Cutover",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-11-01",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-11-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    },
    {
      "id": 601,
      "projectId": 6,
      "milestoneId": "MS-01",
      "title": "OBD-II Hardware Installation on First 18 Delivery Vans",
      "phase": "Execution",
      "eventType": "Rollout",
      "isPhaseGate": false,
      "baselineDate": "2026-06-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-06-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-06-26",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 602,
      "projectId": 6,
      "milestoneId": "MS-02",
      "title": "Driver Mobile Electronic Proof of Delivery (ePOD) App Pilot",
      "phase": "Execution",
      "eventType": "Testing",
      "isPhaseGate": false,
      "baselineDate": "2026-09-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 603,
      "projectId": 6,
      "milestoneId": "MS-03",
      "title": "Phase Gate 2: Fleet Telematics System Acceptance Signoff",
      "phase": "Closing",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-11-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-11-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    },
    {
      "id": 701,
      "projectId": 7,
      "milestoneId": "MS-01",
      "title": "Structural Mezzanine Steelwork & Sub-Floor Inspection",
      "phase": "Execution",
      "eventType": "Inspection",
      "isPhaseGate": false,
      "baselineDate": "2026-03-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 702,
      "projectId": 7,
      "milestoneId": "MS-02",
      "title": "Cat6A Cabling & Workstation Power Drop Commissioning",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-06-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-06-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-06-28",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 703,
      "projectId": 7,
      "milestoneId": "MS-03",
      "title": "Phase Gate 3: Municipal Building Occupancy Permit & Official Handover",
      "phase": "Closing",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-09-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-09-10",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 801,
      "projectId": 8,
      "milestoneId": "MS-01",
      "title": "Phase Gate 1: Sensor Hardware Specifications & Architecture Signoff",
      "phase": "Planning",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-03-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-30",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 802,
      "projectId": 8,
      "milestoneId": "MS-02",
      "title": "Microcontroller PCB Rev 2.1 Fabrication & Bench Assembly",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-07-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-08-05",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-08-04",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 803,
      "projectId": 8,
      "milestoneId": "MS-03",
      "title": "Thermal Chamber Stress Testing & LoRaWAN Range Validation",
      "phase": "Execution",
      "eventType": "Testing",
      "isPhaseGate": false,
      "baselineDate": "2026-09-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 901,
      "projectId": 9,
      "milestoneId": "MS-01",
      "title": "AI Builder Invoice OCR Template Training on Top 50 Suppliers",
      "phase": "Planning",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-05-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-05-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-05-12",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 902,
      "projectId": 9,
      "milestoneId": "MS-02",
      "title": "Phase Gate 1: Finance Internal Audit Security & Workflow Approval",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-07-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-07-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-07-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 903,
      "projectId": 9,
      "milestoneId": "MS-03",
      "title": "End-to-End User Acceptance Testing (UAT) with 120 Live Invoices",
      "phase": "Testing",
      "eventType": "Testing",
      "isPhaseGate": false,
      "baselineDate": "2026-09-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-09-12",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 904,
      "projectId": 9,
      "milestoneId": "MS-04",
      "title": "Phase Gate 2: Full Production Cutover to Automated 3-Way Match",
      "phase": "Closing",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-10-10",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-10",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 1001,
      "projectId": 10,
      "milestoneId": "MS-01",
      "title": "Geofence Perimeter Survey & Depot Boundary Configuration",
      "phase": "Planning",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-05-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-05-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-05-28",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1002,
      "projectId": 10,
      "milestoneId": "MS-02",
      "title": "Phase Gate 1: Works Council & Employee Privacy Notice Conformance",
      "phase": "Planning",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-06-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-06-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-06-25",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1003,
      "projectId": 10,
      "milestoneId": "MS-03",
      "title": "Payroll Integration & Overtime Rules Calculation Test",
      "phase": "Execution",
      "eventType": "Testing",
      "isPhaseGate": false,
      "baselineDate": "2026-09-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 1101,
      "projectId": 11,
      "milestoneId": "MS-01",
      "title": "SharePoint Standard Operating Procedure (SOP) Document Review",
      "phase": "Planning",
      "eventType": "Audit",
      "isPhaseGate": false,
      "baselineDate": "2026-04-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-04-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-04-28",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1102,
      "projectId": 11,
      "milestoneId": "MS-02",
      "title": "Internal Quality Audit Across All 6 Departments Completed",
      "phase": "Execution",
      "eventType": "Audit",
      "isPhaseGate": false,
      "baselineDate": "2026-07-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-07-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-07-29",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1103,
      "projectId": 11,
      "milestoneId": "MS-03",
      "title": "Phase Gate 1: Executive Management Review & CAPA Closure",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-09-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 1104,
      "projectId": 11,
      "milestoneId": "MS-04",
      "title": "External Registrar Certification Audit & Certificate Re-issue",
      "phase": "Closing",
      "eventType": "Audit",
      "isPhaseGate": true,
      "baselineDate": "2026-10-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    }
  ],
  "risksIssues": [
    {
      "id": 101,
      "projectId": 1,
      "title": "Engineering department dual-tracking with Jira during initial 30-day onboarding",
      "itemType": "Risk",
      "category": "Change Management",
      "likelihood": 2,
      "impact": 3,
      "rating": "Medium",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "Sarah Jenkins",
      "dateRaised": "2026-06-15",
      "description": "Engineering leads requested 30 days of side-by-side operation to build confidence before retiring old ticket trackers."
    },
    {
      "id": 102,
      "projectId": 1,
      "title": "SharePoint list permission scoping across cross-department security groups",
      "itemType": "Risk",
      "category": "Technical",
      "likelihood": 1,
      "impact": 2,
      "rating": "Low",
      "status": "Monitoring",
      "strategy": "Accept",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "Devon Clark",
      "dateRaised": "2026-05-20",
      "description": "Ensure distinct read/write permissions for departmental PMs while preserving Portfolio Director consolidated roll-up access."
    },
    {
      "id": 103,
      "projectId": 1,
      "title": "Legacy Excel status dates format discrepancies in historical project import",
      "itemType": "Issue",
      "category": "Data Quality",
      "likelihood": 3,
      "impact": 2,
      "rating": "Medium",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "Sarah Jenkins",
      "dateRaised": "2026-07-02",
      "description": "Automated Power Automate script built to sanitize date strings during spreadsheet migration; remaining 12 records undergoing manual QA."
    },
    {
      "id": 201,
      "projectId": 2,
      "title": "Warehouse scanner sync API timeout during peak morning order dispatch",
      "itemType": "Issue",
      "category": "Technical",
      "likelihood": 3,
      "impact": 3,
      "rating": "High",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": true,
      "convertedFromRisk": true,
      "owner": "David Vance",
      "dateRaised": "2026-08-10",
      "description": "Batch API calls hitting rate-limit thresholds on warehouse floor; vendor patch queued for weekend deployment."
    },
    {
      "id": 202,
      "projectId": 2,
      "title": "Historical GL account code mapping discrepancies for overseas branch",
      "itemType": "Risk",
      "category": "Finance",
      "likelihood": 2,
      "impact": 2,
      "rating": "Low",
      "status": "Monitoring",
      "strategy": "Mitigate",
      "owner": "Elena Garcia",
      "dateRaised": "2026-07-12",
      "description": "Branch subsidiary used legacy non-standard VAT codes requiring manual chart-of-accounts crosswalk."
    },
    {
      "id": 301,
      "projectId": 3,
      "title": "Client SAML SSO directory integration latency causing authentication timeouts",
      "itemType": "Issue",
      "category": "Security",
      "likelihood": 3,
      "impact": 3,
      "rating": "Critical",
      "status": "Escalated",
      "strategy": "Escalate",
      "sponsorAttentionFlag": true,
      "convertedFromRisk": true,
      "owner": "Amara Diallo",
      "dateRaised": "2026-08-01",
      "description": "Key corporate clients experiencing session dropping on login; external identity specialist engaged."
    },
    {
      "id": 302,
      "projectId": 3,
      "title": "Mobile responsive layout rendering defects on older iOS Safari browsers",
      "itemType": "Risk",
      "category": "Quality",
      "likelihood": 2,
      "impact": 2,
      "rating": "Low",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "owner": "Liam O'Connor",
      "dateRaised": "2026-07-22",
      "description": "CSS grid fallback styles needed for devices running iOS 15 or earlier."
    },
    {
      "id": 401,
      "projectId": 4,
      "title": "Field sales staff foreign travel conditional access IP blocking",
      "itemType": "Risk",
      "category": "Governance",
      "likelihood": 2,
      "impact": 2,
      "rating": "Low",
      "status": "Monitoring",
      "strategy": "Mitigate",
      "owner": "Rachel Wu",
      "dateRaised": "2026-04-10",
      "description": "Configured automated self-service travel notification flow in Teams to exempt trusted devices temporarily."
    },
    {
      "id": 501,
      "projectId": 5,
      "title": "Wi-Fi dead zones in racking aisle 14 causing handheld scanner disconnects",
      "itemType": "Issue",
      "category": "Infrastructure",
      "likelihood": 2,
      "impact": 2,
      "rating": "Medium",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "Devon Clark",
      "dateRaised": "2026-08-05",
      "description": "High-density steel shelving attenuating signal; directional AP installed to restore 5GHz coverage."
    },
    {
      "id": 801,
      "projectId": 8,
      "title": "Custom PCB trace impedance mismatch causing RF packet loss at -20\u00b0C",
      "itemType": "Issue",
      "category": "Engineering",
      "likelihood": 3,
      "impact": 3,
      "rating": "High",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": true,
      "convertedFromRisk": false,
      "owner": "Henrik Lindqvist",
      "dateRaised": "2026-08-02",
      "description": "Rev 2.2 PCB spin ordered with revised dielectric thickness for temperature tolerance."
    },
    {
      "id": 901,
      "projectId": 9,
      "title": "Handwritten notes on utility bills lowering OCR confidence score below 80%",
      "itemType": "Risk",
      "category": "Data Quality",
      "likelihood": 2,
      "impact": 1,
      "rating": "Low",
      "status": "Monitoring",
      "strategy": "Accept",
      "owner": "Elena Garcia",
      "dateRaised": "2026-06-18",
      "description": "Configured exception queue to route ambiguous handwritten slips directly to human clerk for 1-click review."
    }
  ],
  "financials": [
    {
      "projectId": 1,
      "capexApprovedBudget": 48000,
      "opexApprovedBudget": 16000,
      "totalApprovedBudget": 64000,
      "capexPlanCurrentYear": 48000,
      "opexPlanCurrentYear": 16000,
      "capexActualYTD": 38400,
      "opexActualYTD": 12800,
      "capexActualToDate": 38400,
      "opexActualToDate": 12800,
      "actualsToDate": 51200,
      "forecastAtCompletion": 63500,
      "variance": -500,
      "variancePercent": -0.78,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 2,
      "capexApprovedBudget": 185000,
      "opexApprovedBudget": 45000,
      "totalApprovedBudget": 230000,
      "capexPlanCurrentYear": 150000,
      "opexPlanCurrentYear": 35000,
      "capexActualYTD": 142000,
      "opexActualYTD": 39000,
      "capexActualToDate": 142000,
      "opexActualToDate": 39000,
      "actualsToDate": 181000,
      "forecastAtCompletion": 238000,
      "variance": 8000,
      "variancePercent": 3.48,
      "budgetRAG": "Yellow",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 3,
      "capexApprovedBudget": 95000,
      "opexApprovedBudget": 25000,
      "totalApprovedBudget": 120000,
      "capexPlanCurrentYear": 80000,
      "opexPlanCurrentYear": 20000,
      "capexActualYTD": 58000,
      "opexActualYTD": 18000,
      "capexActualToDate": 58000,
      "opexActualToDate": 18000,
      "actualsToDate": 76000,
      "forecastAtCompletion": 126000,
      "variance": 6000,
      "variancePercent": 5.0,
      "budgetRAG": "Yellow",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 4,
      "capexApprovedBudget": 55000,
      "opexApprovedBudget": 22000,
      "totalApprovedBudget": 77000,
      "capexPlanCurrentYear": 55000,
      "opexPlanCurrentYear": 22000,
      "capexActualYTD": 48000,
      "opexActualYTD": 19500,
      "capexActualToDate": 48000,
      "opexActualToDate": 19500,
      "actualsToDate": 67500,
      "forecastAtCompletion": 76000,
      "variance": -1000,
      "variancePercent": -1.3,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 5,
      "capexApprovedBudget": 82000,
      "opexApprovedBudget": 14000,
      "totalApprovedBudget": 96000,
      "capexPlanCurrentYear": 82000,
      "opexPlanCurrentYear": 14000,
      "capexActualYTD": 52000,
      "opexActualYTD": 9000,
      "capexActualToDate": 52000,
      "opexActualToDate": 9000,
      "actualsToDate": 61000,
      "forecastAtCompletion": 95500,
      "variance": -500,
      "variancePercent": -0.52,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 6,
      "capexApprovedBudget": 42000,
      "opexApprovedBudget": 18000,
      "totalApprovedBudget": 60000,
      "capexPlanCurrentYear": 35000,
      "opexPlanCurrentYear": 12000,
      "capexActualYTD": 22000,
      "opexActualYTD": 7000,
      "capexActualToDate": 22000,
      "opexActualToDate": 7000,
      "actualsToDate": 29000,
      "forecastAtCompletion": 59000,
      "variance": -1000,
      "variancePercent": -1.67,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 7,
      "capexApprovedBudget": 280000,
      "opexApprovedBudget": 20000,
      "totalApprovedBudget": 300000,
      "capexPlanCurrentYear": 280000,
      "opexPlanCurrentYear": 20000,
      "capexActualYTD": 265000,
      "opexActualYTD": 18500,
      "capexActualToDate": 265000,
      "opexActualToDate": 18500,
      "actualsToDate": 283500,
      "forecastAtCompletion": 298000,
      "variance": -2000,
      "variancePercent": -0.67,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 8,
      "capexApprovedBudget": 140000,
      "opexApprovedBudget": 35000,
      "totalApprovedBudget": 175000,
      "capexPlanCurrentYear": 120000,
      "opexPlanCurrentYear": 30000,
      "capexActualYTD": 82000,
      "opexActualYTD": 24000,
      "capexActualToDate": 82000,
      "opexActualToDate": 24000,
      "actualsToDate": 106000,
      "forecastAtCompletion": 174000,
      "variance": -1000,
      "variancePercent": -0.57,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 9,
      "capexApprovedBudget": 38000,
      "opexApprovedBudget": 12000,
      "totalApprovedBudget": 50000,
      "capexPlanCurrentYear": 38000,
      "opexPlanCurrentYear": 12000,
      "capexActualYTD": 31000,
      "opexActualYTD": 9500,
      "capexActualToDate": 31000,
      "opexActualToDate": 9500,
      "actualsToDate": 40500,
      "forecastAtCompletion": 49500,
      "variance": -500,
      "variancePercent": -1.0,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 10,
      "capexApprovedBudget": 28000,
      "opexApprovedBudget": 10000,
      "totalApprovedBudget": 38000,
      "capexPlanCurrentYear": 28000,
      "opexPlanCurrentYear": 10000,
      "capexActualYTD": 16000,
      "opexActualYTD": 6000,
      "capexActualToDate": 16000,
      "opexActualToDate": 6000,
      "actualsToDate": 22000,
      "forecastAtCompletion": 37500,
      "variance": -500,
      "variancePercent": -1.32,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 11,
      "capexApprovedBudget": 22000,
      "opexApprovedBudget": 18000,
      "totalApprovedBudget": 40000,
      "capexPlanCurrentYear": 22000,
      "opexPlanCurrentYear": 18000,
      "capexActualYTD": 16500,
      "opexActualYTD": 13500,
      "capexActualToDate": 16500,
      "opexActualToDate": 13500,
      "actualsToDate": 30000,
      "forecastAtCompletion": 39800,
      "variance": -200,
      "variancePercent": -0.5,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    }
  ],
  "changeRequests": [
    {
      "id": 701,
      "projectId": 1,
      "crNumber": "CR-001",
      "title": "Configure Custom Departmental Metadata Taxonomy for Engineering Backlogs",
      "crDate": "2026-05-18",
      "category": "Scope & Taxonomy",
      "type": "Scope & Configuration",
      "costImpact": 0,
      "scheduleImpactWeeks": 0,
      "status": "Approved",
      "approvalStatus": "Approved",
      "requestedDate": "2026-05-18",
      "approvedBy": "Steering Committee (Sarah Jenkins)",
      "justification": "Engineering team required specific technical tags (Firmware, Mechanical, QA) to be filterable inside their departmental portfolio view."
    },
    {
      "id": 702,
      "projectId": 2,
      "crNumber": "CR-002",
      "title": "Add Zebra Print Server Integration Adapter for Dispatch Station 3",
      "crDate": "2026-06-10",
      "category": "Technical Interface",
      "type": "Hardware Integration",
      "costImpact": 4500,
      "scheduleImpactWeeks": 1,
      "status": "Approved",
      "approvalStatus": "Approved",
      "requestedDate": "2026-06-10",
      "approvedBy": "Michael Chang (COO)",
      "justification": "Station 3 packing volume increased by 30%, requiring dedicated high-speed thermal label output directly from ERP packing slip trigger."
    },
    {
      "id": 703,
      "projectId": 3,
      "crNumber": "CR-003",
      "title": "Engage Specialist Identity Contractor for SAML SSO Directory Troubleshooting",
      "crDate": "2026-08-08",
      "category": "External Support",
      "type": "Budget Adjustment",
      "costImpact": 6000,
      "scheduleImpactWeeks": 2,
      "status": "Approved",
      "approvalStatus": "Approved",
      "requestedDate": "2026-08-08",
      "approvedBy": "Jessica Miller (Commercial Director)",
      "justification": "Resolve authentication token mismatch for legacy enterprise customer directories."
    }
  ],
  "teamAllocations": [
    {
      "id": 801,
      "projectId": 1,
      "personName": "Sarah Jenkins",
      "role": "PMO Lead",
      "ftePercent": 80,
      "function": "Project Management"
    },
    {
      "id": 802,
      "projectId": 1,
      "personName": "Devon Clark",
      "role": "M365 Admin",
      "ftePercent": 40,
      "function": "IT & Systems"
    },
    {
      "id": 803,
      "projectId": 1,
      "personName": "Elena Garcia",
      "role": "Department Liaison",
      "ftePercent": 50,
      "function": "Operations & Logistics"
    },
    {
      "id": 804,
      "projectId": 1,
      "personName": "Liam O'Connor",
      "role": "Technical Trainer",
      "ftePercent": 40,
      "function": "Engineering Support"
    },
    {
      "id": 805,
      "projectId": 2,
      "personName": "David Vance",
      "role": "Project Lead",
      "ftePercent": 100,
      "function": "Business Systems"
    },
    {
      "id": 806,
      "projectId": 2,
      "personName": "Elena Garcia",
      "role": "Finance Analyst",
      "ftePercent": 40,
      "function": "Finance"
    },
    {
      "id": 807,
      "projectId": 2,
      "personName": "Marcus Brody",
      "role": "Operations SME",
      "ftePercent": 30,
      "function": "Supply Chain"
    },
    {
      "id": 808,
      "projectId": 3,
      "personName": "Amara Diallo",
      "role": "Lead PM",
      "ftePercent": 100,
      "function": "Digital Solutions"
    },
    {
      "id": 809,
      "projectId": 3,
      "personName": "Liam O'Connor",
      "role": "Full-Stack Dev",
      "ftePercent": 60,
      "function": "Software Engineering"
    },
    {
      "id": 810,
      "projectId": 4,
      "personName": "Rachel Wu",
      "role": "Security Lead",
      "ftePercent": 90,
      "function": "Cybersecurity"
    },
    {
      "id": 811,
      "projectId": 4,
      "personName": "Alexander Wright",
      "role": "Systems Engineer",
      "ftePercent": 50,
      "function": "IT Systems"
    },
    {
      "id": 812,
      "projectId": 5,
      "personName": "Devon Clark",
      "role": "Project Lead",
      "ftePercent": 60,
      "function": "Logistics Systems"
    },
    {
      "id": 813,
      "projectId": 5,
      "personName": "Henrik Lindqvist",
      "role": "Hardware Specialist",
      "ftePercent": 40,
      "function": "Operations Engineering"
    },
    {
      "id": 814,
      "projectId": 6,
      "personName": "Liam O'Connor",
      "role": "Project Manager",
      "ftePercent": 40,
      "function": "Fleet Management"
    },
    {
      "id": 815,
      "projectId": 6,
      "personName": "Marcus Brody",
      "role": "Operations Director",
      "ftePercent": 20,
      "function": "Supply Chain"
    },
    {
      "id": 816,
      "projectId": 7,
      "personName": "Sarah Jenkins",
      "role": "Project Sponsor / PM",
      "ftePercent": 20,
      "function": "Facilities Management"
    },
    {
      "id": 817,
      "projectId": 7,
      "personName": "Elena Garcia",
      "role": "Contract Administrator",
      "ftePercent": 20,
      "function": "Operations"
    },
    {
      "id": 818,
      "projectId": 8,
      "personName": "Henrik Lindqvist",
      "role": "Lead Hardware Engineer",
      "ftePercent": 100,
      "function": "Product Design"
    },
    {
      "id": 819,
      "projectId": 8,
      "personName": "Priya Patel",
      "role": "Embedded Firmware Dev",
      "ftePercent": 80,
      "function": "Embedded Systems"
    },
    {
      "id": 820,
      "projectId": 9,
      "personName": "Elena Garcia",
      "role": "Process Owner",
      "ftePercent": 50,
      "function": "Finance"
    },
    {
      "id": 821,
      "projectId": 9,
      "personName": "David Vance",
      "role": "Technical Architect",
      "ftePercent": 30,
      "function": "Business Systems"
    },
    {
      "id": 822,
      "projectId": 10,
      "personName": "Priya Patel",
      "role": "HR Project Lead",
      "ftePercent": 20,
      "function": "Workforce Ops"
    },
    {
      "id": 823,
      "projectId": 10,
      "personName": "Sarah Jenkins",
      "role": "PMO Advisor",
      "ftePercent": 10,
      "function": "Project Management"
    },
    {
      "id": 824,
      "projectId": 11,
      "personName": "Alexander Wright",
      "role": "Quality Manager",
      "ftePercent": 50,
      "function": "Quality Assurance"
    },
    {
      "id": 825,
      "projectId": 11,
      "personName": "Henrik Lindqvist",
      "role": "Engineering Auditor",
      "ftePercent": 20,
      "function": "Engineering Governance"
    }
  ],
  "monthlyStatus": [
    {
      "id": 901,
      "projectId": 1,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "Project reached 80% total completion milestone. IT Infrastructure and Operations & Supply Chain departments are now operating 100% inside PPM Compass 360. Engineering department onboarded into staging environment with 28 active users.",
      "achievements": "Departments 1 & 2 weekly status meetings conducted directly using PPM Compass 360 live dashboard, completely retiring old Excel tracker. Zero data leakage outside M365 tenant confirmed by IT security audit.",
      "nextMonthPlan": "Complete final user training cohort for Engineering team leads; conduct Phase Gate 3 final governance review for business-as-usual handover.",
      "nextSteps": "Complete final user training cohort for Engineering team leads; conduct Phase Gate 3 final governance review.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Sarah Jenkins (PMO Lead)"
    },
    {
      "id": 902,
      "projectId": 1,
      "reportingMonth": "July 2026",
      "period": "July 2026",
      "rag": "Green",
      "summary": "Phase Gate 2 compliance verification passed with zero security remarks. Department 2 (Operations & Supply Chain) completed cutover and initial portfolio sync.",
      "achievements": "Migrated 14 active Operations projects from Excel into SharePoint lists without data disruption. Portfolio picker customized with department tags.",
      "nextMonthPlan": "Initiate Department 3 (Engineering & R&D) sandbox configuration and user training.",
      "nextSteps": "Initiate Department 3 sandbox configuration and user training.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-07-31",
      "reportedBy": "Sarah Jenkins (PMO Lead)"
    },
    {
      "id": 903,
      "projectId": 1,
      "reportingMonth": "June 2026",
      "period": "June 2026",
      "rag": "Green",
      "summary": "Department 1 (IT Infrastructure) pilot declared successful. Executive steering committee approved progression to Phase 2 multi-department expansion.",
      "achievements": "SPFx web part installed in tenant app catalog; all security assessments cleared by IT leadership. 12 IT projects actively tracked.",
      "nextMonthPlan": "Begin Operations department data cleansing and schema mapping.",
      "nextSteps": "Begin Operations department data cleansing and schema mapping.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-06-30",
      "reportedBy": "Sarah Jenkins (PMO Lead)"
    },
    {
      "id": 904,
      "projectId": 2,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Yellow",
      "summary": "Integration testing continues across distribution branches. Budget variance flagged due to additional vendor specialist hours for barcode sync.",
      "achievements": "Data migration completed across all 14 branch accounting schemas without data corruption.",
      "nextMonthPlan": "Finalize barcode timeout patch with software vendor; complete pre-go-live readiness rehearsal.",
      "nextSteps": "Finalize barcode timeout patch with software vendor; complete pre-go-live readiness rehearsal.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "David Vance"
    },
    {
      "id": 905,
      "projectId": 2,
      "reportingMonth": "July 2026",
      "period": "July 2026",
      "rag": "Green",
      "summary": "Core General Ledger and AP/AR modules configured in sandbox. User acceptance test scripts drafted for warehouse leads.",
      "achievements": "Chart of accounts validated by external audit partner.",
      "nextMonthPlan": "Execute end-to-end purchasing test scenarios with live supplier catalogs.",
      "nextSteps": "Execute end-to-end purchasing test scenarios with live supplier catalogs.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-07-31",
      "reportedBy": "David Vance"
    },
    {
      "id": 906,
      "projectId": 3,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Red",
      "summary": "Go-live delayed due to client SAML SSO directory integration latency. New identity contractor onboarding this week to accelerate token bridge.",
      "achievements": "Customer order status search and PDF invoice generation tests passed with sub-second response times.",
      "nextMonthPlan": "Deploy revised SAML handler to staging; conduct pilot with 5 friendly customer accounts.",
      "nextSteps": "Deploy revised SAML handler to staging; conduct pilot with 5 friendly customer accounts.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Amara Diallo"
    },
    {
      "id": 907,
      "projectId": 4,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "Intune device compliance and BitLocker disk encryption achieved on 100% of staff laptops. Third-party pen test scheduled for next week.",
      "achievements": "Phishing simulation test revealed 97% pass rate, up from 78% baseline in January.",
      "nextMonthPlan": "Complete external penetration test and obtain formal ISO 27001 readiness statement.",
      "nextSteps": "Complete external penetration test and obtain formal ISO 27001 readiness statement.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Rachel Wu"
    },
    {
      "id": 908,
      "projectId": 5,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Yellow",
      "summary": "45 handheld mobile scanners staged and configured. Training schedules compressed to recover from 10-day hardware shipping delay.",
      "achievements": "Warehouse Wi-Fi mesh signal test confirmed strong coverage across all 18 pallet racking aisles.",
      "nextMonthPlan": "Conduct pilot pick-and-pack shift with day crew; measure scan-to-manifest throughput.",
      "nextSteps": "Conduct pilot pick-and-pack shift with day crew; measure scan-to-manifest throughput.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Devon Clark"
    },
    {
      "id": 909,
      "projectId": 6,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "First 18 delivery vans equipped with GPS telematics dongles. Route optimization software yielding 14% fuel reduction in early trials.",
      "achievements": "Electronic proof-of-delivery (ePOD) app deployed to driver tablets with zero sync errors.",
      "nextMonthPlan": "Complete hardware installation on remaining 10 vehicles; roll out customer SMS arrival alerts.",
      "nextSteps": "Complete hardware installation on remaining 10 vehicles; roll out customer SMS arrival alerts.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Liam O'Connor"
    },
    {
      "id": 910,
      "projectId": 7,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "Construction 100% complete and official municipal occupancy certificate granted. Supervisor workstations operational.",
      "achievements": "Project completed under budget with $2,000 contingency remaining and zero safety incidents.",
      "nextMonthPlan": "Execute final financial closeout and release contractor retention bond.",
      "nextSteps": "Execute final financial closeout and release contractor retention bond.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Sarah Jenkins"
    },
    {
      "id": 911,
      "projectId": 8,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Yellow",
      "summary": "Rev 2.2 PCB layout finished to address cold-temperature trace impedance. Environmental thermal chamber booking confirmed.",
      "achievements": "Sleep mode current draw optimized to 9.8uA, comfortably beating the 12uA target for 5-year battery life.",
      "nextMonthPlan": "Assemble 10 prototype units with rev 2.2 boards and complete CE pre-compliance testing.",
      "nextSteps": "Assemble 10 prototype units with rev 2.2 boards and complete CE pre-compliance testing.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Henrik Lindqvist"
    },
    {
      "id": 912,
      "projectId": 9,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "UAT completed with 120 live supplier invoices achieving 94.2% zero-touch extraction. Finance team enthusiastically approves go-live.",
      "achievements": "Exception handling workflow confirmed to route ambiguous invoices within 30 seconds to accounting queue.",
      "nextMonthPlan": "Transition all 50 top suppliers to automated PDF intake mailbox; retire manual paper processing.",
      "nextSteps": "Transition all 50 top suppliers to automated PDF intake mailbox.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Elena Garcia"
    },
    {
      "id": 913,
      "projectId": 10,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "Mobile geofenced clock-in operating smoothly across 60 warehouse workers with 99% check-in compliance.",
      "achievements": "Zero punch buddy discrepancies reported during the first 30 days of side-by-side run.",
      "nextMonthPlan": "Implement automated bi-weekly payroll export to cloud ERP; decommission physical wall clocks.",
      "nextSteps": "Implement automated bi-weekly payroll export to cloud ERP.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Priya Patel"
    },
    {
      "id": 914,
      "projectId": 11,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "Internal audits completed across all 6 departments. All minor corrective actions closed out in SharePoint document register.",
      "achievements": "Executive management review meeting held with 100% director attendance and signed audit charter.",
      "nextMonthPlan": "Host external registrar auditor for stage 1 documentation assessment in mid-September.",
      "nextSteps": "Host external registrar auditor for stage 1 documentation assessment in mid-September.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Alexander Wright"
    }
  ]
};
