/**
 * PPM Compass 360 - Realistic Multi-Department Dataset for Small & Mid-Sized Enterprises (SMEs)
 * Featuring 3 Departmental PPM Compass Rollouts (IT: 3-month Completed, Operations: 3-week Execution, Engineering: 3-week Planning)
 */

window.PPM_DEMO_DATA = {
  "portfolios": [
    {
      "id": "all",
      "name": "All Portfolios"
    },
    {
      "id": "enterprise",
      "name": "IT Systems & Infrastructure"
    },
    {
      "id": "operations",
      "name": "Operations & Supply Chain"
    },
    {
      "id": "engineering",
      "name": "Engineering & Product Design"
    },
    {
      "id": "digital",
      "name": "Customer Solutions & Digital"
    },
    {
      "id": "facilities",
      "name": "Facilities & Real Estate"
    },
    {
      "id": "finance",
      "name": "Finance & Corporate Services"
    }
  ],
  "projects": [
    {
      "id": 1,
      "code": "PPM-101",
      "title": "PPM Compass 360 \u2014 IT Dept Portfolio Implementation",
      "portfolio": "enterprise",
      "portfolioName": "IT Systems & Infrastructure",
      "type": "M365 Tenant Implementation",
      "phase": "Close",
      "priority": "Critical",
      "overallStatus": "Completed",
      "lead": "Sarah Jenkins",
      "leadEmail": "s.jenkins@contoso.com",
      "deputy": "Devon Clark",
      "sponsor": "David Vance (VP Technology & Risk)",
      "erpCode": "PPM-2026-IT",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Initial tenant deployment and IT portfolio completed in 3 months. M365 security cleared, 14 IT projects migrated from Excel, and team operational in BAU.",
      "percentComplete": 100,
      "startDate": "2026-03-01",
      "targetDate": "2026-05-31",
      "description": "Initial enterprise rollout of PPM Compass 360 for IT & Cloud Infrastructure, including M365 tenant security review, SPFx app catalog deployment, PM training, and legacy Excel migration (3-month total duration). Managed 100% internally by PMO and IT staff with zero external consulting fees (3.990 € site license + internal hours).",
      "goal": "Establish verified in-tenant governance baseline, secure IT security sign-off, and transition IT project portfolio out of spreadsheets.",
      "scope": "Tenant SPFx approval, automated SharePoint list provisioning, IT project schema customization, 14 PMs trained, and historical tracker migration (executed internally to keep implementation costs under 1.800 €).",
      "successMeasures": "Completed within 3 months; zero external data egress verified; 100% IT project visibility on live screen.",
      "projectImageUrl": "/images/projects/it-dept-implementation.jpg",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/PPM-101",
      "mppUrl": "https://contoso.sharepoint.com/sites/PMO/Plans/PPM-IT-Implementation.mpp",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PPM-IT-Rollout",
      "lastStatusUpdate": "2026-05-31"
    },
    {
      "id": 2,
      "code": "PPM-102",
      "title": "PPM Compass 360 — Operations Portfolio Rollout",
      "portfolio": "operations",
      "portfolioName": "Operations & Supply Chain",
      "type": "Fast-Track Rollout",
      "phase": "Execute",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Devon Clark",
      "leadEmail": "d.clark@contoso.com",
      "deputy": "Elena Garcia",
      "sponsor": "Marcus Brody (Director of Supply Chain)",
      "erpCode": "PPM-2026-OPS",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Rapid 3-week department rollout tracking on schedule at 75% completion. Operations site collection activated and active projects ingested; final team walkthrough next week.",
      "percentComplete": 75,
      "startDate": "2026-08-15",
      "targetDate": "2026-09-08",
      "description": "Department 2 rapid expansion of PPM Compass 360 for Operations & Supply Chain. Leverages existing tenant app catalog approval for a fast 3-week cutover. Implemented internally by operations leads to keep total costs low (3.990 € site license + 800 € internal PMO onboarding).",
      "goal": "Unify logistics, warehouse, and fleet projects under standardized portfolio governance with zero new server setup.",
      "scope": "Operations site collection activation, custom logistics metadata views, 8 project managers trained, and active project roster cutover (executed internally with zero external consulting).",
      "successMeasures": "Deployment completed in 3 weeks; 100% Operations team adoption; weekly review conducted on live screen.",
      "projectImageUrl": "/images/projects/operations-rollout.jpg",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/PPM-102",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PPM-Ops-Rollout",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 3,
      "code": "PPM-103",
      "title": "PPM Compass 360 — Engineering Portfolio Rollout",
      "portfolio": "engineering",
      "portfolioName": "Engineering & Product Design",
      "type": "Fast-Track Rollout",
      "phase": "Plan",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Sarah Jenkins",
      "leadEmail": "s.jenkins@contoso.com",
      "deputy": "Henrik Lindqvist",
      "sponsor": "Dr. Aris Thorne (VP Product Engineering)",
      "erpCode": "PPM-2026-ENG",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Planning phase complete for 3-week cutover. Stage-gate taxonomy and custom R&D milestone templates approved by Engineering VP.",
      "percentComplete": 25,
      "startDate": "2026-09-01",
      "targetDate": "2026-09-22",
      "description": "Department 3 rapid onboarding of PPM Compass 360 for Engineering & R&D projects. 3-week cutover scheduled following successful IT and Operations rollouts. Managed internally with zero consultant overhead (3.990 € site license + 800 € internal PMO onboarding).",
      "goal": "Standardize hardware and firmware project stage-gate tracking in SharePoint with zero IT friction.",
      "scope": "Engineering metadata configuration, sprint/gate milestone mapping, 10 team leads trained, and spreadsheet retirement (internal PMO onboarding, zero consulting spend).",
      "successMeasures": "Cutover completed in 3 weeks; elimination of 6 departmental spreadsheets.",
      "projectImageUrl": "/images/projects/engineering-rollout.jpg",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/PPM-103",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PPM-Eng-Rollout",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 4,
      "code": "ERP-201",
      "title": "Cloud ERP Migration & Warehouse Inventory Sync",
      "portfolio": "enterprise",
      "portfolioName": "IT Systems & Infrastructure",
      "type": "Business Systems",
      "phase": "Execute",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "David Vance",
      "leadEmail": "d.vance@contoso.com",
      "deputy": "Elena Garcia",
      "sponsor": "Michael Chang (COO & Head of Operations)",
      "erpCode": "ERP-2026-02",
      "ragOverall": "Yellow",
      "ragTimeline": "Yellow",
      "ragBudget": "Yellow",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Integration testing with regional warehouse identified 2 barcode scanning interface delays; supplier patch scheduled for testing next week.",
      "percentComplete": 78,
      "startDate": "2025-10-01",
      "targetDate": "2026-11-15",
      "description": "Transition of legacy on-premise accounting and inventory database to cloud ERP, linking purchasing, sales orders, and regional warehouse dispatch.",
      "goal": "Eliminate manual double-entry of packing slips and provide unified inventory counts across branches.",
      "scope": "Core general ledger, accounts payable/receivable, warehouse stock sync, and role-based branch manager dashboards.",
      "successMeasures": "99.5% inventory ledger reconciliation accuracy, zero lost orders during cutover, and automated invoice delivery.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/ERP-201",
      "mppUrl": "https://contoso.sharepoint.com/sites/PMO/Plans/ERP-Cloud-Migration.mpp",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/ERP-Migration",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 5,
      "code": "CRM-202",
      "title": "B2B Customer Portal & Self-Service Order Tracking",
      "portfolio": "digital",
      "portfolioName": "Customer Solutions & Digital",
      "type": "Customer Experience",
      "phase": "Execute",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Amara Diallo",
      "leadEmail": "a.diallo@contoso.com",
      "deputy": "Liam O'Connor",
      "sponsor": "Jessica Miller (Commercial Director)",
      "erpCode": "CRM-9801",
      "ragOverall": "Red",
      "ragTimeline": "Red",
      "ragBudget": "Yellow",
      "ragResources": "Red",
      "ragScope": "Green",
      "ragReason": "Customer single sign-on (SSO) SAML identity integration with legacy client directory delayed by 3 weeks; external contractor assigned to assist.",
      "percentComplete": 54,
      "startDate": "2026-02-01",
      "targetDate": "2026-10-31",
      "description": "Secure web portal enabling B2B commercial clients to review real-time order fulfillment status, download invoices, and request re-orders.",
      "goal": "Reduce routine inbound customer inquiry calls by 40% while accelerating order repeat rate.",
      "scope": "Customer authentication portal, ERP order lookup API, PDF invoice retrieval, and email tracking notifications.",
      "successMeasures": "Sub-1 second catalog search, 40% reduction in status calls to sales reps, and positive feedback from top 20 clients.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/CRM-202",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/B2B-Portal",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 6,
      "code": "CYB-203",
      "title": "M365 Zero-Trust Security & ISO 27001 Baseline",
      "portfolio": "enterprise",
      "portfolioName": "IT Systems & Infrastructure",
      "type": "Cybersecurity & Compliance",
      "phase": "Execute",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Rachel Wu",
      "leadEmail": "r.wu@contoso.com",
      "deputy": "Alexander Wright",
      "sponsor": "David Vance (VP Technology & Risk)",
      "erpCode": "SEC-4412",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Phishing simulation and endpoint protection rollout completed on all 280 staff workstations ahead of schedule.",
      "percentComplete": 88,
      "startDate": "2026-01-10",
      "targetDate": "2026-09-30",
      "description": "Implementation of Microsoft Defender for Endpoint, Intune MDM compliance policies, conditional access MFA, and SharePoint sensitivity classification.",
      "goal": "Achieve comprehensive cyber resilience and satisfy vendor security questionnaire requirements for enterprise clients.",
      "scope": "Intune deployment, conditional access policy enforcement, BitLocker disk encryption, and automated phishing training.",
      "successMeasures": "100% staff compliance on hardware MFA, zero critical vulnerability findings in external penetration test.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/CYB-203",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/Cyber-ZeroTrust",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 7,
      "code": "OPS-301",
      "title": "Warehouse Barcode Scanning & Pick-and-Pack Automation",
      "portfolio": "operations",
      "portfolioName": "Operations & Supply Chain",
      "type": "Supply Chain",
      "phase": "Execute",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Devon Clark",
      "leadEmail": "d.clark@contoso.com",
      "deputy": "Henrik Lindqvist",
      "sponsor": "Marcus Brody (Director of Supply Chain)",
      "erpCode": "OPS-5501",
      "ragOverall": "Yellow",
      "ragTimeline": "Yellow",
      "ragBudget": "Green",
      "ragResources": "Yellow",
      "ragScope": "Green",
      "ragReason": "Zebra wireless hand scanners shipment arrived 10 days late; floor staff staging sessions compressed into evening shifts.",
      "percentComplete": 62,
      "startDate": "2026-03-15",
      "targetDate": "2026-11-15",
      "description": "Deployment of ruggedized handheld barcode scanners and thermal label printers integrated directly with cloud inventory stock records.",
      "goal": "Cut order picking errors by 70% and eliminate paper-based warehouse manifest sheets.",
      "scope": "45 handheld mobile scanners, warehouse Wi-Fi mesh expansion, pallet barcoding, and picker verification workflows.",
      "successMeasures": "Pick error rate under 0.1%, pick-to-pack throughput increased by 28% across 2 warehouse zones.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/OPS-301",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/Warehouse-Automation",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 8,
      "code": "LOG-302",
      "title": "Regional Delivery Fleet GPS Routing & Telematics",
      "portfolio": "operations",
      "portfolioName": "Operations & Supply Chain",
      "type": "Logistics & Fleet",
      "phase": "Execute",
      "priority": "Medium",
      "overallStatus": "Running",
      "lead": "Liam O'Connor",
      "leadEmail": "l.oconnor@contoso.com",
      "deputy": "Marcus Brody",
      "sponsor": "Marcus Brody (Director of Supply Chain)",
      "erpCode": "FLEET-620",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Hardware telemetry dongles installed across first 18 delivery vans; route optimization software showing 14% fuel savings in pilot.",
      "percentComplete": 45,
      "startDate": "2026-04-01",
      "targetDate": "2026-12-15",
      "description": "Installation of OBD-II GPS telematics across commercial delivery fleet with dynamic route planning and electronic delivery signatures.",
      "goal": "Optimize daily delivery drops, reduce fleet fuel expenditure, and provide customers with accurate delivery ETA alerts.",
      "scope": "28 commercial vans, GPS tracking hardware, mobile electronic proof-of-delivery (ePOD) app, and dispatch dashboard.",
      "successMeasures": "15% average route fuel reduction, on-time delivery rate exceeding 96%.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/LOG-302",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/Fleet-Telematics",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 9,
      "code": "FAC-401",
      "title": "Central Distribution Center Office & Mezzanine Expansion",
      "portfolio": "facilities",
      "portfolioName": "Facilities & Real Estate",
      "type": "Facility & Infrastructure",
      "phase": "Close",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Sarah Jenkins",
      "leadEmail": "s.jenkins@contoso.com",
      "deputy": "Elena Garcia",
      "sponsor": "Michael Chang (COO & Head of Operations)",
      "erpCode": "FAC-9011",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Final building inspector signoff and municipal occupancy permit received; snagging punch-list 95% cleared.",
      "percentComplete": 92,
      "startDate": "2025-11-01",
      "targetDate": "2026-09-30",
      "description": "Construction of 4,000 sq ft structural steel mezzanine, 8 operational supervisor workstations, breakroom, and low-voltage network cabling.",
      "goal": "Expand logistics administrative footprint without requiring an expensive secondary warehouse lease.",
      "scope": "Mezzanine engineering, HVAC ducting extension, Cat6A network drops, LED lighting, and ergonomic furniture installation.",
      "successMeasures": "Zero lost-time safety incidents during construction, completed within 2% of approved contingency budget.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/FAC-401",
      "mppUrl": "https://contoso.sharepoint.com/sites/PMO/Plans/Mezzanine-Expansion.mpp",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/Facility-Expansion",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 10,
      "code": "ENG-501",
      "title": "Next-Gen Compact Sensor Hardware Prototyping",
      "portfolio": "engineering",
      "portfolioName": "Engineering & Product Design",
      "type": "R&D & Product Engineering",
      "phase": "Execute",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Henrik Lindqvist",
      "leadEmail": "h.lindqvist@contoso.com",
      "deputy": "Priya Patel",
      "sponsor": "Dr. Aris Thorne (VP of Product Engineering)",
      "erpCode": "ENG-202",
      "ragOverall": "Yellow",
      "ragTimeline": "Yellow",
      "ragBudget": "Green",
      "ragResources": "Yellow",
      "ragScope": "Green",
      "ragReason": "Custom microcontroller PCB rev 2.1 required trace impedance adjustments; environmental chamber testing delayed by 12 business days.",
      "percentComplete": 65,
      "startDate": "2026-01-15",
      "targetDate": "2026-11-30",
      "description": "Design, firmware engineering, and laboratory stress validation for new low-power industrial telemetry sensor line.",
      "goal": "Deliver battery-operated sensor with 5-year operating lifespan and Bluetooth LE / LoRaWAN wireless telemetry.",
      "scope": "Schematic design, 4-layer PCB layout, embedded C firmware, IP67 waterproof enclosure tooling, and CE/FCC pre-scan.",
      "successMeasures": "Current draw under 12uA in sleep mode, radio range over 800 meters, successful CE compliance testing.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/ENG-501",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/Sensor-Prototyping",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 11,
      "code": "FIN-601",
      "title": "Automated Accounts Payable & Invoice OCR Scanning",
      "portfolio": "finance",
      "portfolioName": "Finance & Corporate Services",
      "type": "Finance Process Automation",
      "phase": "Execute",
      "priority": "Medium",
      "overallStatus": "Running",
      "lead": "Elena Garcia",
      "leadEmail": "e.garcia@contoso.com",
      "deputy": "David Vance",
      "sponsor": "Elena Rostova (Finance Director)",
      "erpCode": "FIN-310",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "UAT phase completed with 120 live supplier invoices; OCR recognition rate achieved 94.2% automated matching accuracy.",
      "percentComplete": 82,
      "startDate": "2026-03-01",
      "targetDate": "2026-10-15",
      "description": "Integration of AI optical character recognition (OCR) and Power Automate workflows for automated invoice intake, line-item extraction, and approval routing.",
      "goal": "Accelerate supplier invoice approval from 7 days to 24 hours and capture early payment discounts.",
      "scope": "AI Builder document model training, Power Automate approval flows, ERP Accounts Payable ledger sync, and audit logging.",
      "successMeasures": "85%+ zero-touch invoice processing, reduction of invoice entry labor by 20 hours per week.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/FIN-601",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/AP-Automation",
      "lastStatusUpdate": "2026-08-31"
    }
  ],
  "milestones": [
    {
      "id": 101,
      "projectId": 1,
      "milestoneId": "MS-01",
      "title": "M365 Tenant Security & Architecture Review Board Sign-Off",
      "phase": "Planning",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-03-20",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-20",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-19",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 102,
      "projectId": 1,
      "milestoneId": "MS-02",
      "title": "Tenant SPFx App Catalog Deployment & Schema Provisioning",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-04-10",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-04-10",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-04-09",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 103,
      "projectId": 1,
      "milestoneId": "MS-03",
      "title": "Legacy IT Spreadsheet Ingestion & Data Validation",
      "phase": "Execution",
      "eventType": "Milestone",
      "isPhaseGate": false,
      "baselineDate": "2026-05-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-05-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-05-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 104,
      "projectId": 1,
      "milestoneId": "MS-04",
      "title": "Phase Gate: PM Training & Operational Handover to BAU",
      "phase": "Closing",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-05-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-05-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-05-30",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 201,
      "projectId": 2,
      "milestoneId": "MS-01",
      "title": "Operations Site Collection Activation & Schema Setup",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-08-18",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-08-18",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-08-18",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 202,
      "projectId": 2,
      "milestoneId": "MS-02",
      "title": "Logistics Project Data Ingestion & RAG Baseline",
      "phase": "Execution",
      "eventType": "Milestone",
      "isPhaseGate": false,
      "baselineDate": "2026-08-28",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-08-28",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-08-27",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 203,
      "projectId": 2,
      "milestoneId": "MS-03",
      "title": "Phase Gate: Operations Team Training & Final Go-Live Sign-Off",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-09-08",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-08",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 301,
      "projectId": 3,
      "milestoneId": "MS-01",
      "title": "Phase Gate: Engineering Stage-Gate Schema Definition & Approval",
      "phase": "Planning",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-09-05",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-05",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 302,
      "projectId": 3,
      "milestoneId": "MS-02",
      "title": "Active R&D Project Backlog Data Migration",
      "phase": "Execution",
      "eventType": "Milestone",
      "isPhaseGate": false,
      "baselineDate": "2026-09-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    },
    {
      "id": 303,
      "projectId": 3,
      "milestoneId": "MS-03",
      "title": "Lead Engineer Training & Departmental Go-Live",
      "phase": "Execution",
      "eventType": "Go-Live",
      "isPhaseGate": false,
      "baselineDate": "2026-09-22",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-22",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    },
    {
      "id": 401,
      "projectId": 4,
      "milestoneId": "MS-01",
      "title": "Phase Gate 1: Chart of Accounts & General Ledger Structure Approved",
      "phase": "Planning",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2025-12-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2025-12-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2025-12-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 402,
      "projectId": 4,
      "milestoneId": "MS-02",
      "title": "Master Supplier & Customer Data Migration Validated",
      "phase": "Execution",
      "eventType": "Milestone",
      "isPhaseGate": false,
      "baselineDate": "2026-04-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-04-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-05-02",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 403,
      "projectId": 4,
      "milestoneId": "MS-03",
      "title": "Warehouse Barcode Scanning & Real-Time Stock Feed Integration Test",
      "phase": "Execution",
      "eventType": "Testing",
      "isPhaseGate": false,
      "baselineDate": "2026-08-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-10",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 404,
      "projectId": 4,
      "milestoneId": "MS-04",
      "title": "Phase Gate 2: Pre-Go-Live Operational Readiness Review",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-10-01",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    },
    {
      "id": 501,
      "projectId": 5,
      "milestoneId": "MS-01",
      "title": "Customer Persona Wireframes & UI Prototypes Approved",
      "phase": "Planning",
      "eventType": "Sign-off",
      "isPhaseGate": false,
      "baselineDate": "2026-03-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-29",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 502,
      "projectId": 5,
      "milestoneId": "MS-02",
      "title": "Customer SSO & Identity SAML Gateway Integration",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-07-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-05",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Late / Delayed",
      "showOnTimeline": true
    },
    {
      "id": 503,
      "projectId": 5,
      "milestoneId": "MS-03",
      "title": "Phase Gate 2: Client Advisory Council Beta Sign-off",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-09-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-10",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 601,
      "projectId": 6,
      "milestoneId": "MS-01",
      "title": "Phase Gate 1: Conditional Access Security Policy Baselines Approved",
      "phase": "Planning",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-03-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-12",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 602,
      "projectId": 6,
      "milestoneId": "MS-02",
      "title": "Intune Endpoint Protection & Disk Encryption on 280 Laptops",
      "phase": "Execution",
      "eventType": "Rollout",
      "isPhaseGate": false,
      "baselineDate": "2026-06-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-06-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-06-25",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 603,
      "projectId": 6,
      "milestoneId": "MS-03",
      "title": "Phase Gate 2: Third-Party External Penetration Test & Audit Sign-Off",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-09-20",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-20",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 701,
      "projectId": 7,
      "milestoneId": "MS-01",
      "title": "Warehouse Industrial Wi-Fi Mesh Coverage Verification",
      "phase": "Planning",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-05-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-05-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-05-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 702,
      "projectId": 7,
      "milestoneId": "MS-02",
      "title": "45 Handheld Scanner Staging & Firmware Provisioning",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-07-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-08-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-08-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 703,
      "projectId": 7,
      "milestoneId": "MS-03",
      "title": "Shift Picker Training & Batch Scanning Verification",
      "phase": "Execution",
      "eventType": "Training",
      "isPhaseGate": false,
      "baselineDate": "2026-09-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 704,
      "projectId": 7,
      "milestoneId": "MS-04",
      "title": "Phase Gate 2: Full Warehouse Paperless Manifest Cutover",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-11-01",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-11-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    },
    {
      "id": 801,
      "projectId": 8,
      "milestoneId": "MS-01",
      "title": "OBD-II Hardware Installation on First 18 Delivery Vans",
      "phase": "Execution",
      "eventType": "Rollout",
      "isPhaseGate": false,
      "baselineDate": "2026-06-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-06-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-06-26",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 802,
      "projectId": 8,
      "milestoneId": "MS-02",
      "title": "Driver Mobile Electronic Proof of Delivery (ePOD) App Pilot",
      "phase": "Execution",
      "eventType": "Testing",
      "isPhaseGate": false,
      "baselineDate": "2026-09-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 803,
      "projectId": 8,
      "milestoneId": "MS-03",
      "title": "Phase Gate 2: Fleet Telematics System Acceptance Signoff",
      "phase": "Closing",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-11-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-11-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    },
    {
      "id": 901,
      "projectId": 9,
      "milestoneId": "MS-01",
      "title": "Structural Mezzanine Steelwork & Sub-Floor Inspection",
      "phase": "Execution",
      "eventType": "Inspection",
      "isPhaseGate": false,
      "baselineDate": "2026-03-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 902,
      "projectId": 9,
      "milestoneId": "MS-02",
      "title": "Cat6A Cabling & Workstation Power Drop Commissioning",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-06-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-06-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-06-28",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 903,
      "projectId": 9,
      "milestoneId": "MS-03",
      "title": "Phase Gate 3: Municipal Building Occupancy Permit & Official Handover",
      "phase": "Closing",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-09-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-09-10",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1001,
      "projectId": 10,
      "milestoneId": "MS-01",
      "title": "Phase Gate 1: Sensor Hardware Specifications & Architecture Signoff",
      "phase": "Planning",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-03-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-30",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1002,
      "projectId": 10,
      "milestoneId": "MS-02",
      "title": "Microcontroller PCB Rev 2.1 Fabrication & Bench Assembly",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-07-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-08-05",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-08-04",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1003,
      "projectId": 10,
      "milestoneId": "MS-03",
      "title": "Thermal Chamber Stress Testing & LoRaWAN Range Validation",
      "phase": "Execution",
      "eventType": "Testing",
      "isPhaseGate": false,
      "baselineDate": "2026-09-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 1101,
      "projectId": 11,
      "milestoneId": "MS-01",
      "title": "AI Builder Invoice OCR Template Training on Top 50 Suppliers",
      "phase": "Planning",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-05-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-05-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-05-12",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1102,
      "projectId": 11,
      "milestoneId": "MS-02",
      "title": "Phase Gate 1: Finance Internal Audit Security & Workflow Approval",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-07-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-07-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-07-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1103,
      "projectId": 11,
      "milestoneId": "MS-03",
      "title": "End-to-End User Acceptance Testing (UAT) with 120 Live Invoices",
      "phase": "Execution",
      "eventType": "Testing",
      "isPhaseGate": false,
      "baselineDate": "2026-09-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-09-12",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1104,
      "projectId": 11,
      "milestoneId": "MS-04",
      "title": "Phase Gate 2: Full Production Cutover to Automated 3-Way Match",
      "phase": "Closing",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-10-10",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-10",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    }
  ],
  "risksIssues": [
    {
      "id": 101,
      "projectId": 1,
      "title": "M365 App Catalog security review required architecture sign-off",
      "itemType": "Risk",
      "category": "Governance",
      "likelihood": 2,
      "impact": 2,
      "rating": "Low",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "owner": "Sarah Jenkins",
      "dateRaised": "2026-03-10",
      "description": "Completed security architecture questionnaire; confirmed 100% in-tenant zero-egress architecture."
    },
    {
      "id": 201,
      "projectId": 2,
      "title": "Logistics shift managers require evening training session availability",
      "itemType": "Risk",
      "category": "Change Management",
      "likelihood": 2,
      "impact": 2,
      "rating": "Low",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "owner": "Devon Clark",
      "dateRaised": "2026-08-20",
      "description": "Scheduled recorded 30-minute walkthrough sessions in Microsoft Stream for shift supervisors."
    },
    {
      "id": 301,
      "projectId": 3,
      "title": "Engineering team leads request custom firmware gate taxonomy tags",
      "itemType": "Risk",
      "category": "Scope",
      "likelihood": 1,
      "impact": 2,
      "rating": "Low",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "owner": "Sarah Jenkins",
      "dateRaised": "2026-09-02",
      "description": "Customized SharePoint choice columns to support Hardware/Firmware/Validation stage gate tags."
    },
    {
      "id": 401,
      "projectId": 4,
      "title": "Warehouse scanner sync API timeout during peak morning order dispatch",
      "itemType": "Issue",
      "category": "Technical",
      "likelihood": 3,
      "impact": 3,
      "rating": "High",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": true,
      "convertedFromRisk": true,
      "owner": "David Vance",
      "dateRaised": "2026-08-10",
      "description": "Batch API calls hitting rate-limit thresholds on warehouse floor; vendor patch queued for weekend deployment."
    },
    {
      "id": 501,
      "projectId": 5,
      "title": "Client SAML SSO directory integration latency causing authentication timeouts",
      "itemType": "Issue",
      "category": "Security",
      "likelihood": 3,
      "impact": 3,
      "rating": "Critical",
      "status": "Escalated",
      "strategy": "Escalate",
      "sponsorAttentionFlag": true,
      "convertedFromRisk": true,
      "owner": "Amara Diallo",
      "dateRaised": "2026-08-01",
      "description": "Key corporate clients experiencing session dropping on login; external identity specialist engaged."
    }
  ],
  "financials": [
    {
      "projectId": 1,
      "capexApprovedBudget": 3990,
      "opexApprovedBudget": 1800,
      "totalApprovedBudget": 5790,
      "capexPlanCurrentYear": 3990,
      "opexPlanCurrentYear": 1800,
      "capexActualYTD": 3990,
      "opexActualYTD": 1650,
      "capexActualToDate": 3990,
      "opexActualToDate": 1650,
      "actualsToDate": 5640,
      "forecastAtCompletion": 5640,
      "variance": -150,
      "variancePercent": -2.59,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-05-31"
    },
    {
      "projectId": 2,
      "capexApprovedBudget": 3990,
      "opexApprovedBudget": 800,
      "totalApprovedBudget": 4790,
      "capexPlanCurrentYear": 3990,
      "opexPlanCurrentYear": 800,
      "capexActualYTD": 3990,
      "opexActualYTD": 600,
      "capexActualToDate": 3990,
      "opexActualToDate": 600,
      "actualsToDate": 4590,
      "forecastAtCompletion": 4750,
      "variance": -40,
      "variancePercent": -0.84,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-08-31"
    },
    {
      "projectId": 3,
      "capexApprovedBudget": 3990,
      "opexApprovedBudget": 800,
      "totalApprovedBudget": 4790,
      "capexPlanCurrentYear": 3990,
      "opexPlanCurrentYear": 800,
      "capexActualYTD": 0,
      "opexActualYTD": 200,
      "capexActualToDate": 0,
      "opexActualToDate": 200,
      "actualsToDate": 200,
      "forecastAtCompletion": 4790,
      "variance": 0,
      "variancePercent": 0.0,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-08-31"
    },
    {
      "projectId": 4,
      "capexApprovedBudget": 185000,
      "opexApprovedBudget": 45000,
      "totalApprovedBudget": 230000,
      "capexPlanCurrentYear": 150000,
      "opexPlanCurrentYear": 35000,
      "capexActualYTD": 142000,
      "opexActualYTD": 39000,
      "capexActualToDate": 142000,
      "opexActualToDate": 39000,
      "actualsToDate": 181000,
      "forecastAtCompletion": 238000,
      "variance": 8000,
      "variancePercent": 3.48,
      "budgetRAG": "Yellow",
      "lastFinanceSync": "2026-08-31"
    },
    {
      "projectId": 5,
      "capexApprovedBudget": 95000,
      "opexApprovedBudget": 25000,
      "totalApprovedBudget": 120000,
      "capexPlanCurrentYear": 8000,
      "opexPlanCurrentYear": 20000,
      "capexActualYTD": 58000,
      "opexActualYTD": 18000,
      "capexActualToDate": 58000,
      "opexActualToDate": 18000,
      "actualsToDate": 76000,
      "forecastAtCompletion": 126000,
      "variance": 6000,
      "variancePercent": 5.0,
      "budgetRAG": "Yellow",
      "lastFinanceSync": "2026-08-31"
    },
    {
      "projectId": 6,
      "capexApprovedBudget": 55000,
      "opexApprovedBudget": 22000,
      "totalApprovedBudget": 77000,
      "capexPlanCurrentYear": 55000,
      "opexPlanCurrentYear": 22000,
      "capexActualYTD": 48000,
      "opexActualYTD": 19500,
      "capexActualToDate": 48000,
      "opexActualToDate": 19500,
      "actualsToDate": 67500,
      "forecastAtCompletion": 76000,
      "variance": -1000,
      "variancePercent": -1.3,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-08-31"
    },
    {
      "projectId": 7,
      "capexApprovedBudget": 82000,
      "opexApprovedBudget": 14000,
      "totalApprovedBudget": 96000,
      "capexPlanCurrentYear": 82000,
      "opexPlanCurrentYear": 14000,
      "capexActualYTD": 52000,
      "opexActualYTD": 9000,
      "capexActualToDate": 52000,
      "opexActualToDate": 9000,
      "actualsToDate": 61000,
      "forecastAtCompletion": 95500,
      "variance": -500,
      "variancePercent": -0.52,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-08-31"
    },
    {
      "projectId": 8,
      "capexApprovedBudget": 42000,
      "opexApprovedBudget": 18000,
      "totalApprovedBudget": 60000,
      "capexPlanCurrentYear": 35000,
      "opexPlanCurrentYear": 12000,
      "capexActualYTD": 22000,
      "opexActualYTD": 7000,
      "capexActualToDate": 22000,
      "opexActualToDate": 7000,
      "actualsToDate": 29000,
      "forecastAtCompletion": 59000,
      "variance": -1000,
      "variancePercent": -1.67,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-08-31"
    },
    {
      "projectId": 9,
      "capexApprovedBudget": 280000,
      "opexApprovedBudget": 20000,
      "totalApprovedBudget": 300000,
      "capexPlanCurrentYear": 280000,
      "opexPlanCurrentYear": 20000,
      "capexActualYTD": 265000,
      "opexActualYTD": 18500,
      "capexActualToDate": 265000,
      "opexActualToDate": 18500,
      "actualsToDate": 283500,
      "forecastAtCompletion": 298000,
      "variance": -2000,
      "variancePercent": -0.67,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-08-31"
    },
    {
      "projectId": 10,
      "capexApprovedBudget": 140000,
      "opexApprovedBudget": 35000,
      "totalApprovedBudget": 175000,
      "capexPlanCurrentYear": 120000,
      "opexPlanCurrentYear": 30000,
      "capexActualYTD": 82000,
      "opexActualYTD": 24000,
      "capexActualToDate": 82000,
      "opexActualToDate": 24000,
      "actualsToDate": 106000,
      "forecastAtCompletion": 174000,
      "variance": -1000,
      "variancePercent": -0.57,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-08-31"
    },
    {
      "projectId": 11,
      "capexApprovedBudget": 38000,
      "opexApprovedBudget": 12000,
      "totalApprovedBudget": 50000,
      "capexPlanCurrentYear": 38000,
      "opexPlanCurrentYear": 12000,
      "capexActualYTD": 31000,
      "opexActualYTD": 9500,
      "capexActualToDate": 31000,
      "opexActualToDate": 9500,
      "actualsToDate": 40500,
      "forecastAtCompletion": 49500,
      "variance": -500,
      "variancePercent": -1.0,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-08-31"
    }
  ],
  "changeRequests": [
    {
      "id": 701,
      "projectId": 1,
      "crNumber": "CR-001",
      "title": "Add Custom SharePoint Views for Infrastructure Cloud Sprint Backlogs",
      "crDate": "2026-04-18",
      "category": "Scope & Configuration",
      "type": "Configuration",
      "costImpact": 0,
      "scheduleImpactWeeks": 0,
      "status": "Approved",
      "approvalStatus": "Approved",
      "requestedDate": "2026-04-18",
      "approvedBy": "David Vance (VP Tech)",
      "justification": "IT leads requested custom view filters by cloud platform (Azure / AWS / On-Prem)."
    },
    {
      "id": 702,
      "projectId": 2,
      "crNumber": "CR-002",
      "title": "Add Distribution Depot Column to Operations Project Roster",
      "crDate": "2026-08-22",
      "category": "Metadata",
      "type": "Configuration",
      "costImpact": 0,
      "scheduleImpactWeeks": 0,
      "status": "Approved",
      "approvalStatus": "Approved",
      "requestedDate": "2026-08-22",
      "approvedBy": "Marcus Brody (Director)",
      "justification": "Allows filtering projects by warehouse location (North Depot, Central DC, South Hub)."
    }
  ],
  "teamAllocations": [
    {
      "id": 801,
      "projectId": 1,
      "personName": "Sarah Jenkins",
      "role": "PMO Lead",
      "ftePercent": 80,
      "function": "Project Management"
    },
    {
      "id": 802,
      "projectId": 1,
      "personName": "Devon Clark",
      "role": "M365 Admin",
      "ftePercent": 40,
      "function": "IT & Systems"
    },
    {
      "id": 803,
      "projectId": 1,
      "personName": "Alexander Wright",
      "role": "IT Engineer",
      "ftePercent": 30,
      "function": "IT Infrastructure"
    },
    {
      "id": 804,
      "projectId": 2,
      "personName": "Devon Clark",
      "role": "Project Lead",
      "ftePercent": 60,
      "function": "Logistics Systems"
    },
    {
      "id": 805,
      "projectId": 2,
      "personName": "Elena Garcia",
      "role": "Department Liaison",
      "ftePercent": 40,
      "function": "Operations"
    },
    {
      "id": 806,
      "projectId": 2,
      "personName": "Marcus Brody",
      "role": "Operations SME",
      "ftePercent": 20,
      "function": "Supply Chain"
    },
    {
      "id": 807,
      "projectId": 3,
      "personName": "Sarah Jenkins",
      "role": "PMO Lead",
      "ftePercent": 30,
      "function": "Project Management"
    },
    {
      "id": 808,
      "projectId": 3,
      "personName": "Henrik Lindqvist",
      "role": "Lead Hardware Eng",
      "ftePercent": 30,
      "function": "Product Design"
    },
    {
      "id": 809,
      "projectId": 3,
      "personName": "Priya Patel",
      "role": "Firmware Dev",
      "ftePercent": 20,
      "function": "Embedded Systems"
    },
    {
      "id": 810,
      "projectId": 4,
      "personName": "David Vance",
      "role": "Project Lead",
      "ftePercent": 100,
      "function": "Business Systems"
    },
    {
      "id": 811,
      "projectId": 4,
      "personName": "Elena Garcia",
      "role": "Finance Analyst",
      "ftePercent": 40,
      "function": "Finance"
    },
    {
      "id": 812,
      "projectId": 5,
      "personName": "Amara Diallo",
      "role": "Lead PM",
      "ftePercent": 100,
      "function": "Digital Solutions"
    },
    {
      "id": 813,
      "projectId": 5,
      "personName": "Liam O'Connor",
      "role": "Full-Stack Dev",
      "ftePercent": 60,
      "function": "Software Engineering"
    },
    {
      "id": 814,
      "projectId": 6,
      "personName": "Rachel Wu",
      "role": "Security Lead",
      "ftePercent": 90,
      "function": "Cybersecurity"
    },
    {
      "id": 815,
      "projectId": 7,
      "personName": "Devon Clark",
      "role": "Project Lead",
      "ftePercent": 40,
      "function": "Logistics Systems"
    },
    {
      "id": 816,
      "projectId": 8,
      "personName": "Liam O'Connor",
      "role": "Project Manager",
      "ftePercent": 40,
      "function": "Fleet Management"
    },
    {
      "id": 817,
      "projectId": 9,
      "personName": "Sarah Jenkins",
      "role": "Project PM",
      "ftePercent": 20,
      "function": "Facilities Management"
    },
    {
      "id": 818,
      "projectId": 10,
      "personName": "Henrik Lindqvist",
      "role": "Lead Engineer",
      "ftePercent": 70,
      "function": "Product Design"
    },
    {
      "id": 819,
      "projectId": 11,
      "personName": "Elena Garcia",
      "role": "Process Owner",
      "ftePercent": 50,
      "function": "Finance"
    }
  ],
  "monthlyStatus": [
    {
      "id": 901,
      "projectId": 1,
      "reportingMonth": "May 2026",
      "period": "May 2026",
      "rag": "Green",
      "summary": "Project successfully completed 100% on schedule within 3 months. All 14 IT infrastructure projects migrated into PPM Compass 360 with 0 spreadsheet dependencies remaining.",
      "achievements": "Full IT security and compliance approval verified; IT PMO weekly reviews running live in SharePoint with zero external data egress.",
      "nextMonthPlan": "Project closed. Department operating in Business-as-Usual. Lessons learned shared with Operations and Engineering for pipeline rollouts.",
      "nextSteps": "Project closed. Department operating in Business-as-Usual.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-05-31",
      "reportedBy": "Sarah Jenkins (PMO Lead)"
    },
    {
      "id": 902,
      "projectId": 1,
      "reportingMonth": "April 2026",
      "period": "April 2026",
      "rag": "Green",
      "summary": "Tenant app catalog deployment completed. Automated SharePoint lists provisioning verified across all test sites.",
      "achievements": "Migration script validated against historical Excel records with 100% data integrity.",
      "nextMonthPlan": "Conduct final user training cohort for 14 IT project leaders and complete cutover.",
      "nextSteps": "Conduct final user training cohort and complete cutover.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-04-30",
      "reportedBy": "Sarah Jenkins (PMO Lead)"
    },
    {
      "id": 903,
      "projectId": 1,
      "reportingMonth": "March 2026",
      "period": "March 2026",
      "rag": "Green",
      "summary": "M365 Tenant Security & Architecture Review Board sign-off achieved. Solution package (.sppkg) validated by IT administrators.",
      "achievements": "Zero external API endpoints and 100% in-tenant privacy architecture confirmed by security team.",
      "nextMonthPlan": "Deploy SPFx package to tenant app catalog and provision baseline SharePoint lists.",
      "nextSteps": "Deploy SPFx package to tenant app catalog.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-03-31",
      "reportedBy": "Sarah Jenkins (PMO Lead)"
    },
    {
      "id": 904,
      "projectId": 2,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "Rapid 3-week rollout on track at 75% progress. Operations site collection activated and 8 active logistics projects ingested directly from spreadsheets.",
      "achievements": "Cutover executed in under 2 weeks leveraging pre-approved tenant app catalog. Operations leadership conducted first live portfolio review.",
      "nextMonthPlan": "Finalize shift supervisor training; complete formal go-live signoff by September 8th.",
      "nextSteps": "Finalize shift supervisor training; complete formal go-live signoff.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Devon Clark (Project Lead)"
    },
    {
      "id": 905,
      "projectId": 3,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "Project initiated for 3-week fast-track cutover starting September 1st. Stage-gate schema and custom R&D milestone templates approved by Engineering VP.",
      "achievements": "Pre-configured SharePoint site collection provisioned in 10 minutes. Backlog project list prioritized for import.",
      "nextMonthPlan": "Execute active project migration and conduct team lead training; achieve departmental go-live by September 22nd.",
      "nextSteps": "Execute active project migration and conduct team lead training.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Sarah Jenkins (PMO Lead)"
    },
    {
      "id": 906,
      "projectId": 4,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Yellow",
      "summary": "Integration testing continues across distribution branches. Barcode sync timeout patch scheduled with vendor for weekend deployment.",
      "achievements": "Data migration completed across all 14 branch accounting schemas without data corruption.",
      "nextMonthPlan": "Finalize barcode timeout patch with software vendor; complete pre-go-live readiness rehearsal.",
      "nextSteps": "Finalize barcode timeout patch with software vendor; complete pre-go-live readiness rehearsal.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "David Vance"
    },
    {
      "id": 907,
      "projectId": 5,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Red",
      "summary": "Go-live delayed due to client SAML SSO directory integration latency. External identity specialist onboarding this week.",
      "achievements": "Customer order status search and PDF invoice generation tests passed with sub-second response times.",
      "nextMonthPlan": "Deploy revised SAML handler to staging; conduct pilot with 5 friendly customer accounts.",
      "nextSteps": "Deploy revised SAML handler to staging; conduct pilot with 5 friendly customer accounts.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Amara Diallo"
    },
    {
      "id": 908,
      "projectId": 6,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "Intune device compliance and BitLocker disk encryption achieved on 100% of staff laptops. Third-party pen test scheduled for next week.",
      "achievements": "Phishing simulation test revealed 97% pass rate, up from 78% baseline in January.",
      "nextMonthPlan": "Complete external penetration test and obtain formal ISO 27001 readiness statement.",
      "nextSteps": "Complete external penetration test and obtain formal ISO 27001 readiness statement.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Rachel Wu"
    },
    {
      "id": 909,
      "projectId": 7,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Yellow",
      "summary": "45 handheld mobile scanners staged and configured. Training schedules compressed to recover from 10-day hardware shipping delay.",
      "achievements": "Warehouse Wi-Fi mesh signal test confirmed strong coverage across all 18 pallet racking aisles.",
      "nextMonthPlan": "Conduct pilot pick-and-pack shift with day crew; measure scan-to-manifest throughput.",
      "nextSteps": "Conduct pilot pick-and-pack shift with day crew; measure scan-to-manifest throughput.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Devon Clark"
    },
    {
      "id": 910,
      "projectId": 8,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "First 18 delivery vans equipped with GPS telematics dongles. Route optimization software yielding 14% fuel reduction in early trials.",
      "achievements": "Electronic proof-of-delivery (ePOD) app deployed to driver tablets with zero sync errors.",
      "nextMonthPlan": "Complete hardware installation on remaining 10 vehicles; roll out customer SMS arrival alerts.",
      "nextSteps": "Complete hardware installation on remaining 10 vehicles; roll out customer SMS arrival alerts.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Liam O'Connor"
    },
    {
      "id": 911,
      "projectId": 9,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "Construction 100% complete and official municipal occupancy certificate granted. Supervisor workstations operational.",
      "achievements": "Project completed under budget with $2,000 contingency remaining and zero safety incidents.",
      "nextMonthPlan": "Execute final financial closeout and release contractor retention bond.",
      "nextSteps": "Execute final financial closeout and release contractor retention bond.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Sarah Jenkins"
    },
    {
      "id": 912,
      "projectId": 10,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Yellow",
      "summary": "Rev 2.2 PCB layout finished to address cold-temperature trace impedance. Environmental thermal chamber booking confirmed.",
      "achievements": "Sleep mode current draw optimized to 9.8uA, comfortably beating the 12uA target for 5-year battery life.",
      "nextMonthPlan": "Assemble 10 prototype units with rev 2.2 boards and complete CE pre-compliance testing.",
      "nextSteps": "Assemble 10 prototype units with rev 2.2 boards and complete CE pre-compliance testing.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Henrik Lindqvist"
    },
    {
      "id": 913,
      "projectId": 11,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "UAT completed with 120 live supplier invoices achieving 94.2% zero-touch extraction. Finance team enthusiastically approves go-live.",
      "achievements": "Exception handling workflow confirmed to route ambiguous invoices within 30 seconds to accounting queue.",
      "nextMonthPlan": "Transition all 50 top suppliers to automated PDF intake mailbox; retire manual paper processing.",
      "nextSteps": "Transition all 50 top suppliers to automated PDF intake mailbox.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Elena Garcia"
    }
  ]
};
