/**
 * PPM Compass 360 - Realistic Multi-Industry Dataset for Small & Mid-Sized Businesses
 * Covering Healthcare Clinics, Manufacturing, Packaging Automation, Facilities, Finance, and IT Systems.
 */

window.PPM_DEMO_DATA = {
  "portfolios": [
    {
      "id": "all",
      "name": "All Portfolios"
    },
    {
      "id": "medtech",
      "name": "Healthcare & Regional Clinics"
    },
    {
      "id": "pharma",
      "name": "Manufacturing & Operations"
    },
    {
      "id": "automotive",
      "name": "Packaging & Industrial Automation"
    },
    {
      "id": "aerospace",
      "name": "Facilities & Office Expansion"
    },
    {
      "id": "fintech",
      "name": "Regional Finance & Credit Unions"
    },
    {
      "id": "enterprise",
      "name": "IT Systems & Business Cloud"
    }
  ],
  "projects": [
    {
      "id": 1,
      "code": "PRJ-101",
      "title": "Cloud & ERP Infrastructure Modernization",
      "portfolio": "enterprise",
      "portfolioName": "IT Systems & Business Cloud",
      "type": "Infrastructure",
      "phase": "Execution",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Sarah Jenkins",
      "leadEmail": "s.jenkins@contoso.com",
      "deputy": "Devon Clark",
      "sponsor": "Michael Chang (Head of IT)",
      "erpCode": "ERP-98421",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Yellow",
      "ragScope": "Green",
      "ragReason": "Resource constraints on senior systems administrator; cross-training underway with minimal timeline impact.",
      "percentComplete": 68,
      "startDate": "2026-01-15",
      "targetDate": "2026-11-30",
      "description": "Migration of on-premises file servers and database workloads to Microsoft Azure and SharePoint with automated backup replication.",
      "goal": "Retire aging local server hardware in head office and improve business continuity and remote team access.",
      "scope": "Cloud workload migration, ExpressRoute/VPN setup, Entra identity sync, and disaster recovery validation.",
      "successMeasures": "Zero business downtime during weekend cutovers, fast response times across branch sites, and SOC2 compliance validation.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/PRJ-101",
      "mppUrl": "https://contoso.sharepoint.com/sites/PMO/Plans/PRJ-101-CloudMigration.mpp",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PRJ-101-CloudMigration",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 2,
      "code": "PRJ-102",
      "title": "Core Invoicing & Financial System Upgrade",
      "portfolio": "enterprise",
      "portfolioName": "IT Systems & Business Cloud",
      "type": "Core Finance",
      "phase": "Testing",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "David Vance",
      "leadEmail": "d.vance@contoso.com",
      "deputy": "Elena Garcia",
      "sponsor": "Elena Rostova (Finance Director)",
      "erpCode": "ERP-10294",
      "ragOverall": "Yellow",
      "ragTimeline": "Yellow",
      "ragBudget": "Red",
      "ragResources": "Green",
      "ragScope": "Yellow",
      "ragReason": "Integration testing with regional warehouse identified 3 interface defects; vendor support hours approved causing slight budget variance.",
      "percentComplete": 82,
      "startDate": "2025-08-01",
      "targetDate": "2026-10-15",
      "description": "Upgrade of company billing, invoicing, and inventory tracking modules across 3 regional branch offices.",
      "goal": "Automate recurring invoice generation and sync real-time stock levels with accounting ledgers.",
      "scope": "Modernize accounting system, redesign 12 client billing templates, and configure automated bank reconciliations.",
      "successMeasures": "Monthly billing cycle reduced from 4 business days to 1 day; 99.8% inventory-to-ledger matching accuracy.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/PRJ-102",
      "mppUrl": "https://contoso.sharepoint.com/sites/PMO/Plans/PRJ-102-S4HANA.mpp",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PRJ-102-ERP-Upgrade",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 3,
      "code": "PRJ-103",
      "title": "Customer Mobile App & Portal 2.0",
      "portfolio": "fintech",
      "portfolioName": "Regional Finance & Credit Unions",
      "type": "Customer Experience",
      "phase": "Execution",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Amara Diallo",
      "leadEmail": "a.diallo@contoso.com",
      "deputy": "Liam O'Connor",
      "sponsor": "Jessica Miller (Head of Customer Operations)",
      "erpCode": "ERP-30198",
      "ragOverall": "Red",
      "ragTimeline": "Red",
      "ragBudget": "Yellow",
      "ragResources": "Red",
      "ragScope": "Green",
      "ragReason": "Biometric FaceID plugin required an SDK patch for iOS 18 compatibility; resubmission delayed app release by 3 weeks.",
      "percentComplete": 54,
      "startDate": "2026-02-01",
      "targetDate": "2026-09-30",
      "description": "Modern mobile app redesign for customer self-service, real-time account balances, and instant digital payments.",
      "goal": "Provide convenient 24/7 mobile access to reduce call center volume by 35% and improve client retention.",
      "scope": "iOS and Android client app, biometric FaceID login, PDF statement downloads, and push notifications for transactions.",
      "successMeasures": "4.8+ App Store rating, 99.9% uptime, and sub-2 second account overview loading speed.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/PRJ-103",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PRJ-103-MobileBank",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 4,
      "code": "PRJ-105",
      "title": "M365 Security & MFA Enforcement",
      "portfolio": "enterprise",
      "portfolioName": "IT Systems & Business Cloud",
      "type": "Cybersecurity",
      "phase": "Execution",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Rachel Wu",
      "leadEmail": "r.wu@contoso.com",
      "deputy": "Marcus Brody",
      "sponsor": "Michael Chang (Head of IT)",
      "erpCode": "ERP-71044",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Multi-factor authentication (MFA) and Conditional Access rolled out across all staff accounts with zero user lockout tickets.",
      "percentComplete": 75,
      "startDate": "2025-11-01",
      "targetDate": "2026-12-15",
      "description": "Implementation of Microsoft Entra ID Conditional Access, automated laptop bitlocker encryption, and phishing-resistant MFA across all 250 employees.",
      "goal": "Eliminate unauthorized account access risks and comply with commercial cyber insurance underwriting standards.",
      "scope": "Microsoft Authenticator rollout, Conditional Access policies by country and device health, and admin role isolation.",
      "successMeasures": "100% staff MFA adoption, 100% company laptop encryption, and approval of annual cyber insurance renewal.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/PRJ-105",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PRJ-105-ZeroTrust",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 5,
      "code": "MED-201",
      "title": "Patient Portal & Clinic EHR Modernization",
      "portfolio": "medtech",
      "portfolioName": "Healthcare & Regional Clinics",
      "type": "Clinical Systems",
      "phase": "Verification",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Dr. Aris Thorne",
      "leadEmail": "a.thorne@contoso.com",
      "deputy": "Dr. Camilla Rossi",
      "sponsor": "Evelyn Vance (Clinical Operations Director)",
      "erpCode": "SAP-MED-901",
      "ragOverall": "Yellow",
      "ragTimeline": "Yellow",
      "ragBudget": "Green",
      "ragResources": "Yellow",
      "ragScope": "Green",
      "ragReason": "Custom lab test result interface required security audit sign-off; testing timeline adjusted by 10 business days.",
      "percentComplete": 62,
      "startDate": "2025-06-01",
      "targetDate": "2027-02-28",
      "description": "Unified patient appointment booking, secure messaging, and Electronic Health Record (EHR) rollout across 4 outpatient clinics.",
      "goal": "Streamline patient check-in, eliminate paper registration forms, and give clinicians instant chart access.",
      "scope": "Patient intake portal, tablet check-in at front desks, secure doctor messaging, and GDPR-compliant patient data hosting.",
      "successMeasures": "Check-in time reduced by 60%, zero data non-conformities during privacy audit, and 90%+ patient satisfaction.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/MED-201",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/MED-201-CardioPulse",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 6,
      "code": "MED-202",
      "title": "Outpatient Clinic Telehealth Kiosk Rollout",
      "portfolio": "medtech",
      "portfolioName": "Healthcare & Regional Clinics",
      "type": "Telehealth",
      "phase": "Design Validation",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Marcus Lindqvist",
      "leadEmail": "m.lindqvist@contoso.com",
      "deputy": "Dr. Camilla Rossi",
      "sponsor": "Prof. Viktor Hauer (Medical Director)",
      "erpCode": "SAP-MED-442",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Pilot consultation booth tested with 30 patients; audio clarity and video privacy received 98% positive feedback.",
      "percentComplete": 48,
      "startDate": "2026-01-10",
      "targetDate": "2027-06-30",
      "description": "Installation of soundproof video consultation booths and vital-sign screening stations in 3 suburban clinic branches.",
      "goal": "Expand specialist medical consultations to regional patients without requiring travel to the main hospital center.",
      "scope": "Hardware procurement, touchscreens, high-res medical cameras, integrated digital stethoscope, and encrypted video link.",
      "successMeasures": "Over 200 remote consultations completed monthly, under 1 minute connection setup, and positive clinician feedback.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/MED-202",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/MED-202-NeuroNav",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 7,
      "code": "MED-203",
      "title": "Pharmacy Cold-Chain Storage & Inventory Sync",
      "portfolio": "medtech",
      "portfolioName": "Healthcare & Regional Clinics",
      "type": "Medical Supply",
      "phase": "Execution",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Dr. Henriette Moreau",
      "leadEmail": "h.moreau@contoso.com",
      "deputy": "David Vance",
      "sponsor": "Evelyn Vance (Operations Director)",
      "erpCode": "SAP-MED-108",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Yellow",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Wireless IoT refrigeration sensors calibrated; automated SMS alerts for temperature excursions verified with emergency staff.",
      "percentComplete": 74,
      "startDate": "2025-09-01",
      "targetDate": "2026-12-20",
      "description": "Continuous IoT temperature monitoring and automated reordering for temperature-sensitive medications and vaccines.",
      "goal": "Prevent inventory spoilage, ensure healthcare regulatory compliance, and automate replenishment from wholesale suppliers.",
      "scope": "Smart sensors in 18 medical refrigerators, automated cloud logging, SMS alert escalation, and ERP stock sync.",
      "successMeasures": "Zero medication spoilage incidents, automated compliance reporting for health authorities, and 100% sensor battery uptime.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/MED-203",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/MED-203-GlucoSense",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 8,
      "code": "PHA-301",
      "title": "ISO 9001:2015 Annual Quality Recertification",
      "portfolio": "pharma",
      "portfolioName": "Manufacturing & Operations",
      "type": "Quality & Compliance",
      "phase": "Testing",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Dr. Henriette Moreau",
      "leadEmail": "h.moreau@contoso.com",
      "deputy": "Sarah Jenkins",
      "sponsor": "Klaus Brandstetter (Quality VP)",
      "erpCode": "SAP-PHA-773",
      "ragOverall": "Yellow",
      "ragTimeline": "Yellow",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Yellow",
      "ragReason": "Internal pre-audit identified 2 calibration procedure documentation gaps; corrective action plan submitted on schedule.",
      "percentComplete": 58,
      "startDate": "2025-10-01",
      "targetDate": "2026-11-15",
      "description": "Annual quality management audit across plant manufacturing, vendor supplier qualification, and standard operating procedures (SOP).",
      "goal": "Maintain ISO 9001:2015 certification required by major industrial customers and supply chain partners.",
      "scope": "Review of 85 operating procedures, audit of 14 key component suppliers, management review meetings, and external registrar inspection.",
      "successMeasures": "Zero major non-conformities, full recertification grant, and closure of all preventative action requests.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/PHA-301",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PHA-301-mRNA",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 9,
      "code": "AUT-401",
      "title": "Packaging Line Robotics & Automated Boxing",
      "portfolio": "automotive",
      "portfolioName": "Packaging & Industrial Automation",
      "type": "Automation & Ops",
      "phase": "Testing",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Stefan Weber",
      "leadEmail": "s.weber@contoso.com",
      "deputy": "Henrik Lindqvist",
      "sponsor": "Dieter Braun (Plant Operations Manager)",
      "erpCode": "SAP-AUT-520",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "Robotic pick-and-pack arm continuous test run completed 48 hours without jam; box throughput reached 115% of target.",
      "percentComplete": 85,
      "startDate": "2025-04-01",
      "targetDate": "2026-11-30",
      "description": "Installation of two automated delta-robot packaging cells to assemble, label, and shrink-wrap finished products for dispatch.",
      "goal": "Increase packaging throughput by 40% while reducing repetitive strain injuries and manual packing errors.",
      "scope": "Robotic cell assembly, conveyor belt sensor sync, vision system barcode verification, and line operator safety training.",
      "successMeasures": "Throughput exceeding 1,200 cartons/hour, under 0.05% mislabel rate, and complete safety interlock signoff.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/AUT-401",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/AUT-401-Inverter",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 10,
      "code": "AER-501",
      "title": "Regional Commercial Office Fit-Out & Relocation",
      "portfolio": "aerospace",
      "portfolioName": "Facilities & Office Expansion",
      "type": "Facilities & Workplace",
      "phase": "Verification",
      "priority": "Critical",
      "overallStatus": "Running",
      "lead": "Astrid Nygard",
      "leadEmail": "a.nygard@contoso.com",
      "deputy": "Rachel Wu",
      "sponsor": "Thomas Sterling (COO)",
      "erpCode": "SAP-AER-301",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "High-speed structured fiber cabling and conference room Teams Room AV passed final technical verification.",
      "percentComplete": 90,
      "startDate": "2024-11-01",
      "targetDate": "2026-12-15",
      "description": "Refurbishment and fit-out of a modern 1,200m² regional office space accommodating 120 hybrid employees.",
      "goal": "Consolidate two smaller aging leases into a single energy-efficient hub with collaboration pods and acoustic meeting spaces.",
      "scope": "Architectural partition walls, ergonomic standing desks, Teams Rooms hybrid meeting hardware, secure access badges, and staff move schedule.",
      "successMeasures": "Zero disruption to daily operations, complete move-in on budget, and 28% reduction in monthly facility energy consumption.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/AER-501",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/AER-501-Avionics",
      "lastStatusUpdate": "2026-08-31"
    },
    {
      "id": 11,
      "code": "FIN-502",
      "title": "SEPA Instant Payments & AML Audit Compliance",
      "portfolio": "fintech",
      "portfolioName": "Regional Finance & Credit Unions",
      "type": "Compliance & Payments",
      "phase": "Testing",
      "priority": "High",
      "overallStatus": "Running",
      "lead": "Amara Diallo",
      "leadEmail": "a.diallo@contoso.com",
      "deputy": "David Vance",
      "sponsor": "Jessica Miller (Chief Compliance Officer)",
      "erpCode": "SAP-FIN-881",
      "ragOverall": "Green",
      "ragTimeline": "Green",
      "ragBudget": "Green",
      "ragResources": "Green",
      "ragScope": "Green",
      "ragReason": "SEPA Instant Clearing connection passed end-to-end sandbox tests with regional clearing house; transaction speed under 3 seconds.",
      "percentComplete": 80,
      "startDate": "2025-07-01",
      "targetDate": "2026-11-20",
      "description": "Integration of mandatory EU SEPA Instant Payment rails and automated daily Anti-Money Laundering (AML) sanctions screening.",
      "goal": "Meet European Central Bank regulatory requirements for instant credit transfers and automate compliance reporting.",
      "scope": "Banking API integration, real-time sanctions list matching engine, alert queue for compliance officers, and audit logging.",
      "successMeasures": "Sub-5 second payment confirmation, zero false-negative sanctions matches, and full compliance signoff.",
      "projectImageUrl": "",
      "plannerUrl": "https://tasks.office.com/contoso.com/tasks/FIN-502",
      "mppUrl": "",
      "projectFolderUrl": "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/FIN-502-Settlement",
      "lastStatusUpdate": "2026-08-31"
    }
  ],
  "milestones": [
    {
      "id": 101,
      "projectId": 1,
      "milestoneId": "MS-01",
      "title": "Phase Gate 1: Architecture Review Board Signoff",
      "phase": "Design",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-02-28",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-02-28",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-02-27",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 102,
      "projectId": 1,
      "milestoneId": "MS-02",
      "title": "Tier 1 Datacenter Network ExpressRoute Live",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-04-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-05-05",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-05-04",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 103,
      "projectId": 1,
      "milestoneId": "MS-03",
      "title": "Phase Gate 2: Core Workload Migration Ready",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-08-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-10",
      "forecastDateAccuracy": "Tentative",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 104,
      "projectId": 1,
      "milestoneId": "MS-04",
      "title": "Disaster Recovery Failover Test",
      "phase": "Testing",
      "eventType": "Test",
      "isPhaseGate": false,
      "baselineDate": "2026-09-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-18",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 105,
      "projectId": 1,
      "milestoneId": "MS-05",
      "title": "Executive Sponsor Sign-off & Production Release",
      "phase": "Deployment",
      "eventType": "Sign-off",
      "isPhaseGate": true,
      "baselineDate": "2026-09-28",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 201,
      "projectId": 2,
      "milestoneId": "MS-11",
      "title": "Data Cleansing & Master Data Freeze",
      "phase": "Design",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2025-11-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2025-12-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2025-12-18",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 202,
      "projectId": 2,
      "milestoneId": "MS-12",
      "title": "End-to-End User Acceptance Testing (UAT)",
      "phase": "Testing",
      "eventType": "UAT",
      "isPhaseGate": true,
      "baselineDate": "2026-07-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-15",
      "forecastDateAccuracy": "Tentative",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 203,
      "projectId": 2,
      "milestoneId": "MS-13",
      "title": "Cutover Weekend & Production Go-Live",
      "phase": "Deployment",
      "eventType": "Go-Live",
      "isPhaseGate": true,
      "baselineDate": "2026-09-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Late / Delayed",
      "showOnTimeline": true
    },
    {
      "id": 301,
      "projectId": 3,
      "milestoneId": "MS-21",
      "title": "Security Penetration Testing & OWASP Signoff",
      "phase": "Testing",
      "eventType": "Test",
      "isPhaseGate": true,
      "baselineDate": "2026-06-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-07-20",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-07-25",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 302,
      "projectId": 3,
      "milestoneId": "MS-22",
      "title": "App Store Review Approval (iOS & Android)",
      "phase": "Testing",
      "eventType": "Submission",
      "isPhaseGate": true,
      "baselineDate": "2026-07-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-10",
      "forecastDateAccuracy": "Tentative",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 303,
      "projectId": 3,
      "milestoneId": "MS-23",
      "title": "Public Launch & SEPA Instant Activation",
      "phase": "Deployment",
      "eventType": "Launch",
      "isPhaseGate": true,
      "baselineDate": "2026-08-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Late / Delayed",
      "showOnTimeline": true
    },
    {
      "id": 401,
      "projectId": 4,
      "milestoneId": "MS-31",
      "title": "Conditional Access Pilot Rollout (HQ)",
      "phase": "Execution",
      "eventType": "Launch",
      "isPhaseGate": false,
      "baselineDate": "2026-03-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-30",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 402,
      "projectId": 4,
      "milestoneId": "MS-32",
      "title": "Phase Gate 3: Enterprise PIM Enforcement",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-08-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-08-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-08-28",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 403,
      "projectId": 4,
      "milestoneId": "MS-33",
      "title": "Global Passwordless Cutover Completion",
      "phase": "Deployment",
      "eventType": "Go-Live",
      "isPhaseGate": true,
      "baselineDate": "2026-11-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-11-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 501,
      "projectId": 5,
      "milestoneId": "MS-MD-01",
      "title": "Design History File (DHF) Architecture Freeze",
      "phase": "Design",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2025-10-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2025-11-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2025-11-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 502,
      "projectId": 5,
      "milestoneId": "MS-MD-02",
      "title": "IEC 62304 Class C Firmware Automated V&V",
      "phase": "Verification",
      "eventType": "Test",
      "isPhaseGate": true,
      "baselineDate": "2026-05-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-06-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-06-12",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 503,
      "projectId": 5,
      "milestoneId": "MS-MD-03",
      "title": "ISO 10993 Biocompatibility Toxicological Report",
      "phase": "Verification",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-08-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-25",
      "forecastDateAccuracy": "Tentative",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 504,
      "projectId": 5,
      "milestoneId": "MS-MD-04",
      "title": "Stage Gate: Notified Body EU MDR Annex IX Technical Audit",
      "phase": "Verification",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-11-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-12-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 505,
      "projectId": 5,
      "milestoneId": "MS-MD-05",
      "title": "FDA 510(k) Pre-Market Clearance Formal Grant",
      "phase": "Deployment",
      "eventType": "Approval",
      "isPhaseGate": true,
      "baselineDate": "2027-02-28",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2027-02-28",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    },
    {
      "id": 601,
      "projectId": 6,
      "milestoneId": "MS-MD-11",
      "title": "Sub-millimeter Optical Tracking Stereo Rig Calibration",
      "phase": "Design",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-04-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-04-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-04-10",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 602,
      "projectId": 6,
      "milestoneId": "MS-MD-12",
      "title": "Phase Gate: Cadaveric Usability & Human Factors (IEC 62366)",
      "phase": "Design Validation",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-08-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-08-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-08-27",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 603,
      "projectId": 6,
      "milestoneId": "MS-MD-13",
      "title": "Robotic Kinematics Real-Time Safety Interlock Testing",
      "phase": "Testing",
      "eventType": "Test",
      "isPhaseGate": true,
      "baselineDate": "2026-11-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-11-20",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 604,
      "projectId": 6,
      "milestoneId": "MS-MD-14",
      "title": "Investigational Device Exemption (IDE) Clinical Trial Kickoff",
      "phase": "Deployment",
      "eventType": "Launch",
      "isPhaseGate": true,
      "baselineDate": "2027-03-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2027-03-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "Planned",
      "showOnTimeline": true
    },
    {
      "id": 701,
      "projectId": 7,
      "milestoneId": "MS-MD-21",
      "title": "Enzyme Chemistry Shelf-Life Stability Benchmark",
      "phase": "Design",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-03-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-25",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 702,
      "projectId": 7,
      "milestoneId": "MS-MD-22",
      "title": "Phase Gate: High-Volume Cleanroom Reel-to-Reel Pilot Qualification",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-07-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-08-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-08-14",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 703,
      "projectId": 7,
      "milestoneId": "MS-MD-23",
      "title": "ISO 11607 Sterile Barrier Package Accelerated Aging",
      "phase": "Testing",
      "eventType": "Test",
      "isPhaseGate": false,
      "baselineDate": "2026-10-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-10-20",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 704,
      "projectId": 7,
      "milestoneId": "MS-MD-24",
      "title": "EU IVDR CE Mark Submission & Notified Body Audit",
      "phase": "Deployment",
      "eventType": "Submission",
      "isPhaseGate": true,
      "baselineDate": "2026-12-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-12-20",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 801,
      "projectId": 8,
      "milestoneId": "MS-PHA-01",
      "title": "Phase Gate: 2L to 50L Microfluidic Mixing Tech Transfer",
      "phase": "Design",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-03-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-28",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 802,
      "projectId": 8,
      "milestoneId": "MS-PHA-02",
      "title": "Cleanroom Grade A Isolator Automated VHP Sterilization Cycle",
      "phase": "Execution",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2026-06-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-07-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-07-12",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 803,
      "projectId": 8,
      "milestoneId": "MS-PHA-03",
      "title": "Lipid Nanoparticle Disposable Cassette Shear Stress V&V",
      "phase": "Testing",
      "eventType": "Test",
      "isPhaseGate": true,
      "baselineDate": "2026-08-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-28",
      "forecastDateAccuracy": "Tentative",
      "actualDate": null,
      "status": "At Risk",
      "showOnTimeline": true
    },
    {
      "id": 804,
      "projectId": 8,
      "milestoneId": "MS-PHA-04",
      "title": "Qualified Person (QP) Phase III Clinical Batch Certification",
      "phase": "Deployment",
      "eventType": "Sign-off",
      "isPhaseGate": true,
      "baselineDate": "2026-11-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-11-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 901,
      "projectId": 9,
      "milestoneId": "MS-AUT-01",
      "title": "Silicon Carbide (SiC) Power Module Dyno Efficiency Verification",
      "phase": "Design",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2025-09-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2025-09-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2025-09-26",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 902,
      "projectId": 9,
      "milestoneId": "MS-AUT-02",
      "title": "Phase Gate: ISO 26262 ASIL-D Functional Safety Hardware Freeze",
      "phase": "Execution",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-03-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-03-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-03-29",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 903,
      "projectId": 9,
      "milestoneId": "MS-AUT-03",
      "title": "UNECE R100 Battery Inverter Immersion Thermal Runaway Test",
      "phase": "Testing",
      "eventType": "Test",
      "isPhaseGate": true,
      "baselineDate": "2026-08-31",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-08-31",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-08-28",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 904,
      "projectId": 9,
      "milestoneId": "MS-AUT-04",
      "title": "OEM Pilot Pre-Production Series (SOP-1) Release",
      "phase": "Deployment",
      "eventType": "Go-Live",
      "isPhaseGate": true,
      "baselineDate": "2026-11-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-11-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 1001,
      "projectId": 10,
      "milestoneId": "MS-AER-01",
      "title": "DO-254 Complex Electronic Hardware DAL-A Tool Qualification",
      "phase": "Design",
      "eventType": "Technical",
      "isPhaseGate": false,
      "baselineDate": "2025-06-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2025-06-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2025-06-25",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1002,
      "projectId": 10,
      "milestoneId": "MS-AER-02",
      "title": "Phase Gate: DO-178C Level A 100% MC/DC Test Completion",
      "phase": "Verification",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-02-28",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-02-28",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-02-24",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1003,
      "projectId": 10,
      "milestoneId": "MS-AER-03",
      "title": "RTCA DO-160G Lightning Strike & Magnetic Deflection Rig Test",
      "phase": "Testing",
      "eventType": "Test",
      "isPhaseGate": true,
      "baselineDate": "2026-08-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-08-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-08-10",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1004,
      "projectId": 10,
      "milestoneId": "MS-AER-04",
      "title": "FAA / EASA Type Inspection Authorization (TIA) Flight Tests",
      "phase": "Deployment",
      "eventType": "Approval",
      "isPhaseGate": true,
      "baselineDate": "2026-12-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-12-15",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 1101,
      "projectId": 11,
      "milestoneId": "MS-FIN-01",
      "title": "SWIFT CBPR+ XML Schema Validator Certification",
      "phase": "Design",
      "eventType": "Approval",
      "isPhaseGate": false,
      "baselineDate": "2025-11-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2025-11-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2025-11-28",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1102,
      "projectId": 11,
      "milestoneId": "MS-FIN-02",
      "title": "Phase Gate: High-Throughput 12,000 TPS Stress Load Signoff",
      "phase": "Testing",
      "eventType": "Gate",
      "isPhaseGate": true,
      "baselineDate": "2026-06-30",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-06-30",
      "forecastDateAccuracy": "Exact",
      "actualDate": "2026-06-25",
      "status": "Completed",
      "showOnTimeline": true
    },
    {
      "id": 1103,
      "projectId": 11,
      "milestoneId": "MS-FIN-03",
      "title": "DORA Severe Threat Resiliency Active-Active Cutover Drill",
      "phase": "Testing",
      "eventType": "Test",
      "isPhaseGate": true,
      "baselineDate": "2026-09-15",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-09-20",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    },
    {
      "id": 1104,
      "projectId": 11,
      "milestoneId": "MS-FIN-04",
      "title": "FedNow & TARGET2 Production Payment Rails Go-Live",
      "phase": "Deployment",
      "eventType": "Go-Live",
      "isPhaseGate": true,
      "baselineDate": "2026-11-20",
      "baselineDateAccuracy": "Exact",
      "forecastDate": "2026-11-20",
      "forecastDateAccuracy": "Exact",
      "actualDate": null,
      "status": "On Track",
      "showOnTimeline": true
    }
  ],
  "risksIssues": [
    {
      "id": 101,
      "projectId": 1,
      "title": "SharePoint List item count approaching 5,000 threshold for custom archive views",
      "itemType": "Risk",
      "category": "Technical",
      "likelihood": 3,
      "impact": 2,
      "rating": "High",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "Sarah Jenkins",
      "dateRaised": "2026-02-12",
      "description": "Custom archive views may encounter list view threshold warnings if indexing is not applied prior to sprint 4 data migration."
    },
    {
      "id": 102,
      "projectId": 4,
      "title": "Trial license expiring before vendor procurement approval cycle completes",
      "itemType": "Risk",
      "category": "Commercial",
      "likelihood": 3,
      "impact": 3,
      "rating": "Critical",
      "status": "Escalated",
      "strategy": "Escalate",
      "sponsorAttentionFlag": true,
      "convertedFromRisk": false,
      "owner": "Alexander Wright",
      "dateRaised": "2026-03-03",
      "description": "Formal evaluation period requires sign-off from group legal; procurement cycle takes 4 weeks."
    },
    {
      "id": 1,
      "projectId": 1,
      "title": "DevOps Engineer Capacity Bottleneck",
      "itemType": "Risk",
      "category": "Resource",
      "likelihood": 2,
      "impact": 2,
      "rating": "Medium",
      "status": "Mitigating",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "Sarah Jenkins",
      "dateRaised": "2026-04-10",
      "description": "High demand for Kubernetes engineers across simultaneous enterprise projects creating sprint queue."
    },
    {
      "id": 2,
      "projectId": 1,
      "title": "Frankfurt Legacy SAN Decommission Window",
      "itemType": "Issue",
      "category": "Schedule",
      "likelihood": 3,
      "impact": 2,
      "rating": "High",
      "status": "Monitoring",
      "strategy": "Escalate",
      "sponsorAttentionFlag": true,
      "convertedFromRisk": true,
      "owner": "Devon Clark",
      "dateRaised": "2026-07-15",
      "description": "Facilities management requires physical rack clearance by October 31; requires accelerated cutover for secondary file share."
    },
    {
      "id": 3,
      "projectId": 2,
      "title": "Third-Party EDI Warehouse Interface Timeouts",
      "itemType": "Issue",
      "category": "Technical",
      "likelihood": 3,
      "impact": 3,
      "rating": "Critical",
      "status": "Escalated",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": true,
      "convertedFromRisk": false,
      "owner": "Elena Garcia",
      "dateRaised": "2026-07-02",
      "description": "High-volume order peak in staging triggers HTTP 504 gateway timeouts on legacy AS2 gateway."
    },
    {
      "id": 4,
      "projectId": 2,
      "title": "Overtime Budget Burn Exceeding Forecast",
      "itemType": "Risk",
      "category": "Financial",
      "likelihood": 3,
      "impact": 2,
      "rating": "High",
      "status": "Accepted",
      "strategy": "Accept",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "David Vance",
      "dateRaised": "2026-06-18",
      "description": "Extended contractor hours to support defect triage creating 8% cost overrun; CR-004 submitted."
    },
    {
      "id": 5,
      "projectId": 3,
      "title": "Apple App Store Guideline 5.1 Biometric Rejection",
      "itemType": "Issue",
      "category": "Regulatory & Compliance",
      "likelihood": 3,
      "impact": 3,
      "rating": "Critical",
      "status": "Open",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": true,
      "convertedFromRisk": true,
      "owner": "Amara Diallo",
      "dateRaised": "2026-08-05",
      "description": "Apple review team flagged bundled vendor telemetry library as violating user privacy consent declarations."
    },
    {
      "id": 6,
      "projectId": 4,
      "title": "Legacy Service Accounts Incompatible with Passwordless FIDO2",
      "itemType": "Risk",
      "category": "Technical",
      "likelihood": 2,
      "impact": 1,
      "rating": "Low",
      "status": "Active",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "Marcus Brody",
      "dateRaised": "2026-05-12",
      "description": "Manufacturing SCADA machines rely on fixed service account authentication; deploying managed service identities."
    },
    {
      "id": 7,
      "projectId": 5,
      "title": "ISO 10993 Cytotoxicity Test Turnaround Delay at Notified Body",
      "itemType": "Risk",
      "category": "Regulatory & Compliance",
      "likelihood": 2,
      "impact": 3,
      "rating": "High",
      "status": "Active",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": true,
      "convertedFromRisk": false,
      "owner": "Dr. Aris Thorne",
      "dateRaised": "2026-06-10",
      "description": "External accredited lab backlog delaying 12-week extractable/leachable biocompatibility documentation needed for EU MDR Annex IX submission."
    },
    {
      "id": 8,
      "projectId": 5,
      "title": "IEC 62304 Class C Firmware Static Code Analysis Warnings",
      "itemType": "Issue",
      "category": "Technical",
      "likelihood": 1,
      "impact": 2,
      "rating": "Medium",
      "status": "Active",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": true,
      "owner": "Dr. Camilla Rossi",
      "dateRaised": "2026-07-20",
      "description": "MISRA-C rule violations detected in third-party Bluetooth Low Energy telemetry communication stack; patches underway."
    },
    {
      "id": 9,
      "projectId": 6,
      "title": "Optical Navigation Stereo Camera Ambient IR Interference",
      "itemType": "Risk",
      "category": "Technical",
      "likelihood": 1,
      "impact": 3,
      "rating": "Medium",
      "status": "Active",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "Marcus Lindqvist",
      "dateRaised": "2026-04-05",
      "description": "High-intensity LED surgical overhead lighting in operating theaters can degrade IR marker retro-reflection tracking signal by up to 4%."
    },
    {
      "id": 10,
      "projectId": 7,
      "title": "Reel-to-Reel Enzyme Deposition Strip Coating Variance",
      "itemType": "Issue",
      "category": "Operational",
      "likelihood": 2,
      "impact": 2,
      "rating": "Medium",
      "status": "Active",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "Dr. Henriette Moreau",
      "dateRaised": "2026-05-18",
      "description": "Humidity fluctuations in ISO Class 7 cleanroom caused a 2.4% baseline sensor sensitivity shift across pilot lot 04."
    },
    {
      "id": 11,
      "projectId": 8,
      "title": "Lipid Nanoparticle Microfluidic Nozzle Clogging Under Viscous Flow",
      "itemType": "Issue",
      "category": "Technical",
      "likelihood": 2,
      "impact": 3,
      "rating": "High",
      "status": "Active",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": true,
      "convertedFromRisk": true,
      "owner": "Dr. Henriette Moreau",
      "dateRaised": "2026-07-08",
      "description": "50L scale-up batches experience laminar shear precipitation at high Reynolds numbers; single-use manifold redesign initiated."
    },
    {
      "id": 12,
      "projectId": 9,
      "title": "Silicon Carbide Die Substrate Sourcing Quota Lead Time",
      "itemType": "Risk",
      "category": "Supply Chain",
      "likelihood": 2,
      "impact": 2,
      "rating": "Medium",
      "status": "Active",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "Stefan Weber",
      "dateRaised": "2026-03-22",
      "description": "Global semiconductor fab allocation for 800V SiC MOSFET raw wafers has 22-week lead time; dual-source qualification running in parallel."
    },
    {
      "id": 13,
      "projectId": 10,
      "title": "FAA DER Certification Protocol Scheduling Constraints",
      "itemType": "Risk",
      "category": "Regulatory & Compliance",
      "likelihood": 1,
      "impact": 3,
      "rating": "Medium",
      "status": "Active",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "Astrid Nygard",
      "dateRaised": "2026-02-14",
      "description": "Designated Engineering Representative (DER) audit slots tightly booked for Q4 flight test envelope validation."
    },
    {
      "id": 14,
      "projectId": 11,
      "title": "HSM Cryptographic Key Latency Spike During 12,000 TPS Surge",
      "itemType": "Risk",
      "category": "Performance",
      "likelihood": 1,
      "impact": 2,
      "rating": "Low",
      "status": "Active",
      "strategy": "Mitigate",
      "sponsorAttentionFlag": false,
      "convertedFromRisk": false,
      "owner": "David Vance",
      "dateRaised": "2026-06-11",
      "description": "Hardware Security Module PKCS#11 driver batch signing queue adds 3.2ms latency under simulated FedNow peak load."
    }
  ],
  "financials": [
    {
      "projectId": 1,
      "capexApprovedBudget": 1250000,
      "opexApprovedBudget": 350000,
      "totalApprovedBudget": 1600000,
      "capexPlanCurrentYear": 900000,
      "opexPlanCurrentYear": 250000,
      "capexActualYTD": 840000,
      "opexActualYTD": 210000,
      "capexActualToDate": 840000,
      "opexActualToDate": 210000,
      "actualsToDate": 1050000,
      "forecastAtCompletion": 1580000,
      "variance": -20000,
      "variancePercent": -1.25,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 2,
      "capexApprovedBudget": 2400000,
      "opexApprovedBudget": 850000,
      "totalApprovedBudget": 3250000,
      "capexPlanCurrentYear": 2200000,
      "opexPlanCurrentYear": 800000,
      "capexActualYTD": 2150000,
      "opexActualYTD": 920000,
      "capexActualToDate": 2150000,
      "opexActualToDate": 920000,
      "actualsToDate": 3070000,
      "forecastAtCompletion": 3520000,
      "variance": 270000,
      "variancePercent": 8.31,
      "budgetRAG": "Red",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 3,
      "capexApprovedBudget": 950000,
      "opexApprovedBudget": 280000,
      "totalApprovedBudget": 1230000,
      "capexPlanCurrentYear": 700000,
      "opexPlanCurrentYear": 240000,
      "capexActualYTD": 620000,
      "opexActualYTD": 230000,
      "capexActualToDate": 620000,
      "opexActualToDate": 230000,
      "actualsToDate": 850000,
      "forecastAtCompletion": 1310000,
      "variance": 80000,
      "variancePercent": 6.5,
      "budgetRAG": "Yellow",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 4,
      "capexApprovedBudget": 750000,
      "opexApprovedBudget": 180000,
      "totalApprovedBudget": 930000,
      "capexPlanCurrentYear": 600000,
      "opexPlanCurrentYear": 150000,
      "capexActualYTD": 520000,
      "opexActualYTD": 140000,
      "capexActualToDate": 520000,
      "opexActualToDate": 140000,
      "actualsToDate": 660000,
      "forecastAtCompletion": 915000,
      "variance": -15000,
      "variancePercent": -1.61,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 5,
      "capexApprovedBudget": 3200000,
      "opexApprovedBudget": 890000,
      "totalApprovedBudget": 4090000,
      "capexPlanCurrentYear": 1800000,
      "opexPlanCurrentYear": 550000,
      "capexActualYTD": 1650000,
      "opexActualYTD": 510000,
      "capexActualToDate": 2160000,
      "opexActualToDate": 620000,
      "actualsToDate": 2780000,
      "forecastAtCompletion": 4050000,
      "variance": -40000,
      "variancePercent": -0.98,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 6,
      "capexApprovedBudget": 4500000,
      "opexApprovedBudget": 1200000,
      "totalApprovedBudget": 5700000,
      "capexPlanCurrentYear": 2400000,
      "opexPlanCurrentYear": 700000,
      "capexActualYTD": 2250000,
      "opexActualYTD": 680000,
      "capexActualToDate": 2250000,
      "opexActualToDate": 680000,
      "actualsToDate": 2930000,
      "forecastAtCompletion": 5650000,
      "variance": -50000,
      "variancePercent": -0.88,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 7,
      "capexApprovedBudget": 1900000,
      "opexApprovedBudget": 450000,
      "totalApprovedBudget": 2350000,
      "capexPlanCurrentYear": 1400000,
      "opexPlanCurrentYear": 380000,
      "capexActualYTD": 1420000,
      "opexActualYTD": 420000,
      "capexActualToDate": 1620000,
      "opexActualToDate": 450000,
      "actualsToDate": 2070000,
      "forecastAtCompletion": 2430000,
      "variance": 80000,
      "variancePercent": 3.4,
      "budgetRAG": "Yellow",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 8,
      "capexApprovedBudget": 2800000,
      "opexApprovedBudget": 1100000,
      "totalApprovedBudget": 3900000,
      "capexPlanCurrentYear": 1900000,
      "opexPlanCurrentYear": 750000,
      "capexActualYTD": 1780000,
      "opexActualYTD": 710000,
      "capexActualToDate": 1980000,
      "opexActualToDate": 780000,
      "actualsToDate": 2760000,
      "forecastAtCompletion": 3880000,
      "variance": -20000,
      "variancePercent": -0.51,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 9,
      "capexApprovedBudget": 3600000,
      "opexApprovedBudget": 920000,
      "totalApprovedBudget": 4520000,
      "capexPlanCurrentYear": 2600000,
      "opexPlanCurrentYear": 700000,
      "capexActualYTD": 2550000,
      "opexActualYTD": 690000,
      "capexActualToDate": 3100000,
      "opexActualToDate": 810000,
      "actualsToDate": 3910000,
      "forecastAtCompletion": 4500000,
      "variance": -20000,
      "variancePercent": -0.44,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 10,
      "capexApprovedBudget": 5100000,
      "opexApprovedBudget": 1400000,
      "totalApprovedBudget": 6500000,
      "capexPlanCurrentYear": 3800000,
      "opexPlanCurrentYear": 1100000,
      "capexActualYTD": 3720000,
      "opexActualYTD": 1050000,
      "capexActualToDate": 4650000,
      "opexActualToDate": 1280000,
      "actualsToDate": 5930000,
      "forecastAtCompletion": 6450000,
      "variance": -50000,
      "variancePercent": -0.77,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    },
    {
      "projectId": 11,
      "capexApprovedBudget": 1850000,
      "opexApprovedBudget": 520000,
      "totalApprovedBudget": 2370000,
      "capexPlanCurrentYear": 1450000,
      "opexPlanCurrentYear": 410000,
      "capexActualYTD": 1380000,
      "opexActualYTD": 390000,
      "capexActualToDate": 1580000,
      "opexActualToDate": 440000,
      "actualsToDate": 2020000,
      "forecastAtCompletion": 2340000,
      "variance": -30000,
      "variancePercent": -1.27,
      "budgetRAG": "Green",
      "lastFinanceSync": "2026-09-01"
    }
  ],
  "changeRequests": [
    {
      "id": 701,
      "projectId": 1,
      "crNumber": "CR-001",
      "title": "Add Disaster Recovery Multi-Region Replication for SQL Hyperscale",
      "crDate": "2026-04-18",
      "category": "Scope & Architecture",
      "type": "Scope & Budget",
      "costImpact": 45000,
      "scheduleImpactWeeks": 1,
      "status": "Approved",
      "approvalStatus": "Approved",
      "requestedDate": "2026-04-18",
      "approvedBy": "Michael Chang (CIO)",
      "justification": "Risk assessment mandated secondary geo-redundant standby in North Europe to comply with new regulatory resilience guidelines."
    },
    {
      "id": 702,
      "projectId": 2,
      "crNumber": "CR-004",
      "title": "Extend SAP Integration Specialist Retainer through Cutover",
      "crDate": "2026-07-22",
      "category": "Vendor & Budget",
      "type": "Budget",
      "costImpact": 120000,
      "scheduleImpactWeeks": 2,
      "status": "Approved",
      "approvalStatus": "Approved",
      "requestedDate": "2026-07-22",
      "approvedBy": "Elena Rostova (CFO)",
      "justification": "Critical EDI defects require tier-3 vendor engineers on site throughout UAT and hypercare."
    },
    {
      "id": 703,
      "projectId": 3,
      "crNumber": "CR-008",
      "title": "Biometric SDK Provider Swap & Compliance Rework",
      "crDate": "2026-08-10",
      "category": "Technical",
      "type": "Schedule & Budget",
      "costImpact": 65000,
      "scheduleImpactWeeks": 4,
      "status": "Pending Review",
      "approvalStatus": "Under Review",
      "requestedDate": "2026-08-10",
      "approvedBy": "Pending Steering Committee",
      "justification": "Removes third-party telemetry library to guarantee unconditional Apple and Google store clearance."
    },
    {
      "id": 704,
      "projectId": 5,
      "crNumber": "CR-MED-02",
      "title": "Additional Notified Body Biocompatibility Audit Consultation",
      "crDate": "2026-07-14",
      "category": "Regulatory",
      "type": "Budget",
      "costImpact": 35000,
      "scheduleImpactWeeks": 0,
      "status": "Approved",
      "approvalStatus": "Approved",
      "requestedDate": "2026-07-14",
      "approvedBy": "Evelyn Vance (VP Regulatory)",
      "justification": "Pre-submission review meetings with BSI Notified Body to de-risk Class III cardiovascular biocompatibility protocol."
    },
    {
      "id": 705,
      "projectId": 8,
      "crNumber": "CR-PHA-01",
      "title": "Single-Use Microfluidic Cassette Tooling Redesign",
      "crDate": "2026-08-02",
      "category": "Technical",
      "type": "Budget & Schedule",
      "costImpact": 48000,
      "scheduleImpactWeeks": 2,
      "status": "Approved",
      "approvalStatus": "Approved",
      "requestedDate": "2026-08-02",
      "approvedBy": "Dr. Klaus Brandstetter",
      "justification": "Eliminate shear-induced lipid precipitation during continuous 50L scale-up runs."
    }
  ],
  "teamAllocations": [
    {
      "id": 801,
      "projectId": 1,
      "personName": "Sarah Jenkins",
      "role": "PM",
      "ftePercent": 80,
      "function": "Project Management"
    },
    {
      "id": 802,
      "projectId": 1,
      "personName": "Alex Mercer",
      "role": "Architect",
      "ftePercent": 100,
      "function": "Cloud Architecture"
    },
    {
      "id": 803,
      "projectId": 1,
      "personName": "Devon Clark",
      "role": "Developer",
      "ftePercent": 100,
      "function": "DevOps & Infrastructure"
    },
    {
      "id": 804,
      "projectId": 1,
      "personName": "Priya Patel",
      "role": "QA",
      "ftePercent": 50,
      "function": "Testing & Validation"
    },
    {
      "id": 805,
      "projectId": 2,
      "personName": "David Vance",
      "role": "PM",
      "ftePercent": 100,
      "function": "Project Management"
    },
    {
      "id": 806,
      "projectId": 2,
      "personName": "Jens Moeller",
      "role": "Architect",
      "ftePercent": 100,
      "function": "SAP Solution Architecture"
    },
    {
      "id": 807,
      "projectId": 2,
      "personName": "Elena Garcia",
      "role": "Developer",
      "ftePercent": 100,
      "function": "ABAP / Integration"
    },
    {
      "id": 808,
      "projectId": 2,
      "personName": "Priya Patel",
      "role": "QA",
      "ftePercent": 50,
      "function": "Testing & Validation"
    },
    {
      "id": 809,
      "projectId": 3,
      "personName": "Amara Diallo",
      "role": "PM",
      "ftePercent": 80,
      "function": "Project Management"
    },
    {
      "id": 810,
      "projectId": 3,
      "personName": "Liam O'Connor",
      "role": "Developer",
      "ftePercent": 100,
      "function": "iOS Development"
    },
    {
      "id": 811,
      "projectId": 3,
      "personName": "Sophie Martin",
      "role": "Designer",
      "ftePercent": 60,
      "function": "UI/UX Design"
    },
    {
      "id": 812,
      "projectId": 3,
      "personName": "Kenji Sato",
      "role": "QA",
      "ftePercent": 100,
      "function": "Mobile Automation QA"
    },
    {
      "id": 813,
      "projectId": 4,
      "personName": "Rachel Wu",
      "role": "PM",
      "ftePercent": 100,
      "function": "Cybersecurity PM"
    },
    {
      "id": 814,
      "projectId": 4,
      "personName": "Alex Mercer",
      "role": "Architect",
      "ftePercent": 30,
      "function": "Identity Architecture"
    },
    {
      "id": 815,
      "projectId": 4,
      "personName": "Marcus Brody",
      "role": "Developer",
      "ftePercent": 100,
      "function": "Entra ID & PowerShell"
    },
    {
      "id": 816,
      "projectId": 5,
      "personName": "Dr. Aris Thorne",
      "role": "PM",
      "ftePercent": 100,
      "function": "MedTech Lead"
    },
    {
      "id": 817,
      "projectId": 5,
      "personName": "Dr. Camilla Rossi",
      "role": "Specialist",
      "ftePercent": 90,
      "function": "Biomedical Engineering"
    },
    {
      "id": 818,
      "projectId": 5,
      "personName": "Marcus Lindqvist",
      "role": "QA",
      "ftePercent": 60,
      "function": "V&V / ISO 13485"
    },
    {
      "id": 819,
      "projectId": 6,
      "personName": "Marcus Lindqvist",
      "role": "PM",
      "ftePercent": 80,
      "function": "Robotics PM"
    },
    {
      "id": 820,
      "projectId": 6,
      "personName": "Dr. Camilla Rossi",
      "role": "Specialist",
      "ftePercent": 70,
      "function": "Kinematics Control"
    },
    {
      "id": 821,
      "projectId": 8,
      "personName": "Dr. Henriette Moreau",
      "role": "PM",
      "ftePercent": 90,
      "function": "Pharma R&D Lead"
    },
    {
      "id": 822,
      "projectId": 9,
      "personName": "Stefan Weber",
      "role": "PM",
      "ftePercent": 100,
      "function": "Powertrain Engineering"
    },
    {
      "id": 823,
      "projectId": 10,
      "personName": "Astrid Nygard",
      "role": "PM",
      "ftePercent": 100,
      "function": "Avionics Systems"
    }
  ],
  "monthlyStatus": [
    {
      "id": 901,
      "projectId": 1,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Green",
      "summary": "Completed Tier 1 workloads migration. UAT for database tier approved with 0 Sev-1 issues.",
      "achievements": "ExpressRoute gateway saturated at <35% latency; database cutover rehearsals succeeded without incident.",
      "nextMonthPlan": "Prepare Phase Gate 2 review; kick off disaster recovery failover drill across North and West Europe.",
      "nextSteps": "Prepare Phase Gate 2 review; kick off disaster recovery failover drill.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Sarah Jenkins"
    },
    {
      "id": 902,
      "projectId": 2,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Yellow",
      "summary": "Integration testing continues. Budget variance flagged due to extended vendor specialist engagement.",
      "achievements": "Data migration completed across all 14 distribution center schemas without data corruption.",
      "nextMonthPlan": "Finalize EDI timeout patch with SAP core engineering; submit CR-004 budget adjustment.",
      "nextSteps": "Finalize EDI timeout patch; submit CR-004 budget adjustment.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "David Vance"
    },
    {
      "id": 903,
      "projectId": 3,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Red",
      "summary": "Launch delayed due to store policy guideline rejection on biometric telemetry. New release build 3.0.4 compiled.",
      "achievements": "Customer portal security penetration test passed with zero critical CVEs.",
      "nextMonthPlan": "Resubmit to App Store review team; align customer communication strategy for October go-live.",
      "nextSteps": "Resubmit to App Store review team; align customer communication strategy.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Amara Diallo"
    },
    {
      "id": 904,
      "projectId": 5,
      "reportingMonth": "August 2026",
      "period": "August 2026",
      "rag": "Yellow",
      "summary": "Class III leadless pacemaker V&V protocol executed with 100% telemetry success. External cytotoxicity lab report turnaround tracking for late September.",
      "achievements": "Automated firmware V&V bench completed 50,000 pacing cycle simulations without anomaly.",
      "nextMonthPlan": "Receive accredited lab ISO 10993 biological safety dossier; finalize Notified Body audit submission.",
      "nextSteps": "Receive accredited lab ISO 10993 dossier; finalize Notified Body audit submission.",
      "statusLocked": true,
      "locked": true,
      "submittedDate": "2026-08-31",
      "reportedBy": "Dr. Aris Thorne"
    }
  ]
};
