/**
 * PPM Compass 360 - Realistic Mock Dataset
 * Matches standard SharePoint lists created by the SPFx package:
 * - PM_APP_Projects (Title, ProjectNumber, Goal, Scope, SuccessMeasures, RAGs, Deputy, QuickLinks, Dates)
 * - PM_APP_Milestones (BaselineDate, ForecastDate, ActualDate, Phase, IsPhaseGate, BaselineDateAccuracy)
 * - PM_APP_RisksIssues (SponsorAttentionFlag, Likelihood, Impact, Rating, ResponseStrategy, Owner)
 * - PM_FIN_ProjectFinancials (Opex/Capex Approved Budget, Actual to Date, Plan Current Year, Actual YTD)
 * - PM_APP_ProjectAllocations (MonthYear, AllocationFTE, Role, Function)
 * - PM_APP_ChangeRequests (CRNumber, Title, CRDate, Category, CostImpact, ScheduleImpactWeeks, ApprovalStatus)
 * - PM_APP_MonthlyStatus (ReportingMonth, Achievements, NextMonthPlan, StatusLocked, SubmittedDate)
 */

window.PPM_DEMO_DATA = {
  portfolios: [
    { id: "all", name: "All Portfolios" },
    { id: "digital", name: "Digital Transformation" },
    { id: "operations", name: "Operations & Supply Chain" },
    { id: "infrastructure", name: "Cloud & Infrastructure" },
    { id: "rd", name: "Product & R&D" }
  ],

  projects: [
    {
      id: 1,
      code: "PRJ-101",
      title: "Global Cloud Migration (Wave 2)",
      portfolio: "infrastructure",
      portfolioName: "Cloud & Infrastructure",
      type: "Infrastructure",
      phase: "Execution",
      priority: "Critical",
      overallStatus: "Running",
      lead: "Sarah Jenkins",
      leadEmail: "s.jenkins@contoso.com",
      deputy: "Devon Clark",
      sponsor: "Michael Chang (CIO)",
      erpCode: "ERP-98421",
      ragOverall: "Green",
      ragTimeline: "Green",
      ragBudget: "Green",
      ragResources: "Yellow",
      ragScope: "Green",
      ragReason: "Resource constraints on senior Azure DevOps engineers; cross-skilling underway with minimal timeline impact.",
      percentComplete: 68,
      startDate: "2026-01-15",
      targetDate: "2026-11-30",
      description: "Migration of 48 legacy on-premises workloads to Azure Kubernetes Service and Azure SQL Hyperscale with automated DR replication.",
      goal: "Decommission Tier-2 legacy datacenter in Frankfurt and reduce enterprise infrastructure operating costs by 32%.",
      scope: "Lift-and-shift and containerization of 48 production core services, ExpressRoute setup, and zero-downtime database replication.",
      successMeasures: "Zero Sev-1 outages during cutovers, sub-45ms latency across European regions, and SOC2 compliance validation.",
      projectImageUrl: "",
      plannerUrl: "https://tasks.office.com/contoso.com/tasks/PRJ-101",
      mppUrl: "https://contoso.sharepoint.com/sites/PMO/Plans/PRJ-101-CloudMigration.mpp",
      projectFolderUrl: "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PRJ-101-CloudMigration",
      lastStatusUpdate: "2026-08-31"
    },
    {
      id: 2,
      code: "PRJ-102",
      title: "ERP NextGen S/4HANA Upgrade",
      portfolio: "operations",
      portfolioName: "Operations & Supply Chain",
      type: "Core ERP",
      phase: "Testing",
      priority: "High",
      overallStatus: "Running",
      lead: "David Vance",
      leadEmail: "d.vance@contoso.com",
      deputy: "Elena Garcia",
      sponsor: "Elena Rostova (CFO)",
      erpCode: "ERP-10294",
      ragOverall: "Yellow",
      ragTimeline: "Yellow",
      ragBudget: "Red",
      ragResources: "Green",
      ragScope: "Yellow",
      ragReason: "Integration testing with warehouse management identified 3 critical interface defects; vendor overtime approved causing budget variance.",
      percentComplete: 82,
      startDate: "2025-08-01",
      targetDate: "2026-10-15",
      description: "Enterprise core financial and supply chain modernization. Upgrades SAP modules across 14 European distribution centers.",
      goal: "Modernize ledger and automated warehouse inventory dispatching onto real-time SAP HANA in-memory architecture.",
      scope: "Upgrade SAP ECC 6.0 to S/4HANA Cloud Private Edition, redesigning 18 EDI logistics interfaces and fiscal reporting.",
      successMeasures: "End-of-month financial closing reduced from 5 business days to 18 hours; 99.98% inventory tracking accuracy.",
      projectImageUrl: "",
      plannerUrl: "https://tasks.office.com/contoso.com/tasks/PRJ-102",
      mppUrl: "https://contoso.sharepoint.com/sites/PMO/Plans/PRJ-102-S4HANA.mpp",
      projectFolderUrl: "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PRJ-102-ERP-Upgrade",
      lastStatusUpdate: "2026-08-31"
    },
    {
      id: 3,
      code: "PRJ-103",
      title: "Customer Mobile Banking App 3.0",
      portfolio: "digital",
      portfolioName: "Digital Transformation",
      type: "Customer Experience",
      phase: "Execution",
      priority: "Critical",
      overallStatus: "Running",
      lead: "Amara Diallo",
      leadEmail: "a.diallo@contoso.com",
      deputy: "Liam O'Connor",
      sponsor: "Jessica Miller (Chief Digital Officer)",
      erpCode: "ERP-30198",
      ragOverall: "Red",
      ragTimeline: "Red",
      ragBudget: "Yellow",
      ragResources: "Red",
      ragScope: "Green",
      ragReason: "External biometric authentication SDK failed Apple App Store review v5.1 guidelines; resubmission delayed go-live by 4 weeks.",
      percentComplete: 54,
      startDate: "2026-02-01",
      targetDate: "2026-09-30",
      description: "Redesign of customer-facing mobile banking application with biometric onboarding, real-time AI spending insights, and instant SEPA payments.",
      goal: "Deliver a 4.8+ App Store rated digital banking experience driving a 25% increase in mobile transaction engagement.",
      scope: "Native iOS (Swift) & Android (Kotlin) app, OAuth2 token architecture, biometric FaceID/TouchID security layer, SEPA instant rails.",
      successMeasures: "99.99% login success rate, App Store clearance, and <2 second instant payment settlement.",
      projectImageUrl: "",
      plannerUrl: "https://tasks.office.com/contoso.com/tasks/PRJ-103",
      mppUrl: "",
      projectFolderUrl: "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PRJ-103-MobileBank",
      lastStatusUpdate: "2026-08-31"
    },
    {
      id: 4,
      code: "PRJ-104",
      title: "Automated Fulfillment Logistics (Robotics)",
      portfolio: "operations",
      portfolioName: "Operations & Supply Chain",
      type: "Automation",
      phase: "Design",
      priority: "Medium",
      overallStatus: "On Hold",
      lead: "Henrik Lindqvist",
      leadEmail: "h.lindqvist@contoso.com",
      deputy: "",
      sponsor: "Arthur Pendelton (VP Supply Chain)",
      erpCode: "ERP-48201",
      ragOverall: "Green",
      ragTimeline: "Green",
      ragBudget: "Green",
      ragResources: "Green",
      ragScope: "Green",
      ragReason: "Hardware procurement finalized ahead of plan; pilot site preparation temporarily paused for warehouse facility expansion.",
      percentComplete: 28,
      startDate: "2026-04-10",
      targetDate: "2027-03-31",
      description: "Installation of autonomous automated mobile robots (AMRs) in central logistics hub to accelerate pick-and-pack times by 35%.",
      goal: "Automate pallet transport and carton sorting in Rotterdam distribution center to handle Q4 holiday volume surge.",
      scope: "Deployment of 24 AGVs, fleet management software integration, barcode optical scanner gates, and floor safety grid.",
      successMeasures: "35% increase in pick-and-pack throughput and zero operator safety incidents in pilot quarter.",
      projectImageUrl: "",
      plannerUrl: "https://tasks.office.com/contoso.com/tasks/PRJ-104",
      mppUrl: "",
      projectFolderUrl: "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PRJ-104-Robotics",
      lastStatusUpdate: "2026-07-31"
    },
    {
      id: 5,
      code: "PRJ-105",
      title: "Zero-Trust Enterprise Identity & PAM",
      portfolio: "infrastructure",
      portfolioName: "Cloud & Infrastructure",
      type: "Cybersecurity",
      phase: "Execution",
      priority: "Critical",
      overallStatus: "Running",
      lead: "Rachel Wu",
      leadEmail: "r.wu@contoso.com",
      deputy: "Marcus Brody",
      sponsor: "Michael Chang (CIO)",
      erpCode: "ERP-71044",
      ragOverall: "Green",
      ragTimeline: "Green",
      ragBudget: "Green",
      ragResources: "Green",
      ragScope: "Green",
      ragReason: "Privileged Access Management (PAM) rolled out to Tier 1 domain controllers without operational downtime.",
      percentComplete: 75,
      startDate: "2025-11-01",
      targetDate: "2026-12-15",
      description: "Implementation of Microsoft Entra Privileged Identity Management (PIM) and conditional access zero-trust perimeter across all 12,000 corporate seats.",
      goal: "Eliminate standing administrative privileges and enforce risk-based multi-factor authentication across all hybrid infrastructure.",
      scope: "Entra ID PIM, Just-In-Time access workflows, passwordless FIDO2 rollout, conditional access policies, and audit logging to Microsoft Sentinel.",
      successMeasures: "100% elimination of permanent domain admin accounts and 100% MFA compliance across 12,000 corporate identities.",
      projectImageUrl: "",
      plannerUrl: "https://tasks.office.com/contoso.com/tasks/PRJ-105",
      mppUrl: "",
      projectFolderUrl: "https://contoso.sharepoint.com/sites/PMO/Shared%20Documents/PRJ-105-ZeroTrust",
      lastStatusUpdate: "2026-08-31"
    }
  ],

  milestones: [
    {
      id: 101,
      projectId: 1,
      milestoneId: "MS-01",
      title: "Phase Gate 1: Architecture Review Board Signoff",
      phase: "Design",
      eventType: "Gate",
      isPhaseGate: true,
      baselineDate: "2026-02-28",
      baselineDateAccuracy: "Exact",
      forecastDate: "2026-02-28",
      forecastDateAccuracy: "Exact",
      actualDate: "2026-02-27",
      status: "Completed",
      showOnTimeline: true
    },
    {
      id: 102,
      projectId: 1,
      milestoneId: "MS-02",
      title: "Tier 1 Datacenter Network ExpressRoute Live",
      phase: "Execution",
      eventType: "Technical",
      isPhaseGate: false,
      baselineDate: "2026-04-30",
      baselineDateAccuracy: "Exact",
      forecastDate: "2026-05-05",
      forecastDateAccuracy: "Exact",
      actualDate: "2026-05-04",
      status: "Completed",
      showOnTimeline: true
    },
    {
      id: 103,
      projectId: 1,
      milestoneId: "MS-03",
      title: "Phase Gate 2: Core Workload Migration Ready",
      phase: "Execution",
      eventType: "Gate",
      isPhaseGate: true,
      baselineDate: "2026-08-31",
      baselineDateAccuracy: "Exact",
      forecastDate: "2026-09-10",
      forecastDateAccuracy: "Tentative",
      actualDate: null,
      status: "On Track",
      showOnTimeline: true
    },
    {
      id: 104,
      projectId: 1,
      milestoneId: "MS-04",
      title: "Disaster Recovery Failover Test",
      phase: "Testing",
      eventType: "Test",
      isPhaseGate: false,
      baselineDate: "2026-09-15",
      baselineDateAccuracy: "Exact",
      forecastDate: "2026-09-18",
      forecastDateAccuracy: "Exact",
      actualDate: null,
      status: "On Track",
      showOnTimeline: true
    },
    {
      id: 105,
      projectId: 1,
      milestoneId: "MS-05",
      title: "Executive Sponsor Sign-off & Production Release",
      phase: "Deployment",
      eventType: "Sign-off",
      isPhaseGate: true,
      baselineDate: "2026-09-28",
      baselineDateAccuracy: "Exact",
      forecastDate: "2026-09-30",
      forecastDateAccuracy: "Exact",
      actualDate: null,
      status: "On Track",
      showOnTimeline: true
    },
    {
      id: 201,
      projectId: 2,
      milestoneId: "MS-11",
      title: "Data Cleansing & Master Data Freeze",
      phase: "Design",
      eventType: "Gate",
      isPhaseGate: true,
      baselineDate: "2025-11-30",
      baselineDateAccuracy: "Exact",
      forecastDate: "2025-12-15",
      forecastDateAccuracy: "Exact",
      actualDate: "2025-12-18",
      status: "Completed",
      showOnTimeline: true
    },
    {
      id: 202,
      projectId: 2,
      milestoneId: "MS-12",
      title: "End-to-End User Acceptance Testing (UAT)",
      phase: "Testing",
      eventType: "UAT",
      isPhaseGate: true,
      baselineDate: "2026-07-31",
      baselineDateAccuracy: "Exact",
      forecastDate: "2026-09-15",
      forecastDateAccuracy: "Tentative",
      actualDate: null,
      status: "At Risk",
      showOnTimeline: true
    },
    {
      id: 203,
      projectId: 2,
      milestoneId: "MS-13",
      title: "Cutover Weekend & Production Go-Live",
      phase: "Deployment",
      eventType: "Go-Live",
      isPhaseGate: true,
      baselineDate: "2026-09-30",
      baselineDateAccuracy: "Exact",
      forecastDate: "2026-10-15",
      forecastDateAccuracy: "Exact",
      actualDate: null,
      status: "Delayed",
      showOnTimeline: true
    },
    {
      id: 301,
      projectId: 3,
      milestoneId: "MS-21",
      title: "Security Penetration Testing & OWASP Signoff",
      phase: "Testing",
      eventType: "Test",
      isPhaseGate: true,
      baselineDate: "2026-06-15",
      baselineDateAccuracy: "Exact",
      forecastDate: "2026-07-20",
      forecastDateAccuracy: "Exact",
      actualDate: "2026-07-25",
      status: "Completed",
      showOnTimeline: true
    },
    {
      id: 302,
      projectId: 3,
      milestoneId: "MS-22",
      title: "App Store Review Approval (iOS & Android)",
      phase: "Testing",
      eventType: "Submission",
      isPhaseGate: true,
      baselineDate: "2026-07-31",
      baselineDateAccuracy: "Exact",
      forecastDate: "2026-09-10",
      forecastDateAccuracy: "Tentative",
      actualDate: null,
      status: "Delayed",
      showOnTimeline: true
    },
    {
      id: 303,
      projectId: 3,
      milestoneId: "MS-23",
      title: "Public Release & Customer Migration",
      phase: "Deployment",
      eventType: "Launch",
      isPhaseGate: true,
      baselineDate: "2026-08-31",
      baselineDateAccuracy: "Exact",
      forecastDate: "2026-09-30",
      forecastDateAccuracy: "Tentative",
      actualDate: null,
      status: "At Risk",
      showOnTimeline: true
    }
  ],

  risksIssues: [
    {
      id: 501,
      projectId: 1,
      projectTitle: "Global Cloud Migration (Wave 2)",
      itemType: "Risk",
      title: "Kubernetes Platform Engineer bandwidth shortfall",
      category: "Resource",
      likelihood: 4,
      impact: 3,
      rating: "High (12)",
      severity: "High",
      status: "Mitigating",
      strategy: "Mitigate",
      sponsorAttentionFlag: true,
      owner: "Sarah Jenkins",
      dateRaised: "2026-03-12",
      description: "Specialized AKS engineers are in high demand across enterprise. Onboarding contract DevOps engineer to safeguard sprint velocity."
    },
    {
      id: 502,
      projectId: 2,
      projectTitle: "ERP NextGen S/4HANA Upgrade",
      itemType: "Issue",
      title: "Warehouse Management EDI integration latency failure",
      category: "Technical",
      likelihood: 5,
      impact: 4,
      rating: "Critical (20)",
      severity: "Critical",
      status: "Active",
      strategy: "Mitigate",
      sponsorAttentionFlag: true,
      owner: "David Vance",
      dateRaised: "2026-07-08",
      description: "Batch message processing times out during peak inventory scans. SAP integration patch deployed to test environment for stress testing."
    },
    {
      id: 503,
      projectId: 2,
      projectTitle: "ERP NextGen S/4HANA Upgrade",
      itemType: "Risk",
      title: "Fiscal year-end freeze window overlap",
      category: "Schedule",
      likelihood: 3,
      impact: 4,
      rating: "High (12)",
      severity: "High",
      status: "Active",
      strategy: "Avoid",
      sponsorAttentionFlag: false,
      owner: "Elena Rostova",
      dateRaised: "2026-04-15",
      description: "Deployment timeline encroaches on Finance month-end hard freeze. Contingency cutover schedule prepared for mid-October."
    },
    {
      id: 504,
      projectId: 3,
      projectTitle: "Customer Mobile Banking App 3.0",
      itemType: "Issue",
      title: "App Store rejection under guideline 5.1.1 (Biometric consent)",
      category: "Vendor",
      likelihood: 5,
      impact: 5,
      rating: "Critical (25)",
      severity: "Critical",
      status: "Active",
      strategy: "Mitigate",
      sponsorAttentionFlag: true,
      owner: "Amara Diallo",
      dateRaised: "2026-08-02",
      description: "Apple rejected the build due to third-party SDK telemetry phrasing. Legal and mobile dev updated the consent dialog; resubmitted build 3.0.4."
    },
    {
      id: 505,
      projectId: 3,
      projectTitle: "Customer Mobile Banking App 3.0",
      itemType: "Risk",
      title: "Backend Core Banking API rate limiting under peak load",
      category: "Technical",
      likelihood: 3,
      impact: 3,
      rating: "Medium (9)",
      severity: "Medium",
      status: "Mitigating",
      strategy: "Mitigate",
      sponsorAttentionFlag: false,
      owner: "Amara Diallo",
      dateRaised: "2026-05-19",
      description: "Redis caching layer being introduced on account balance queries to prevent core banking gateway throttling."
    }
  ],

  financials: [
    {
      projectId: 1,
      capexApprovedBudget: 1250000,
      opexApprovedBudget: 350000,
      totalApprovedBudget: 1600000,
      capexPlanCurrentYear: 900000,
      opexPlanCurrentYear: 250000,
      capexActualYTD: 840000,
      opexActualYTD: 210000,
      capexActualToDate: 840000,
      opexActualToDate: 210000,
      actualsToDate: 1050000,
      forecastAtCompletion: 1580000,
      variance: -20000,
      variancePercent: -1.25,
      budgetRAG: "Green",
      lastFinanceSync: "2026-09-01"
    },
    {
      projectId: 2,
      capexApprovedBudget: 2400000,
      opexApprovedBudget: 850000,
      totalApprovedBudget: 3250000,
      capexPlanCurrentYear: 2200000,
      opexPlanCurrentYear: 800000,
      capexActualYTD: 2150000,
      opexActualYTD: 920000,
      capexActualToDate: 2150000,
      opexActualToDate: 920000,
      actualsToDate: 3070000,
      forecastAtCompletion: 3520000,
      variance: 270000,
      variancePercent: 8.31,
      budgetRAG: "Red",
      lastFinanceSync: "2026-09-01"
    },
    {
      projectId: 3,
      capexApprovedBudget: 950000,
      opexApprovedBudget: 280000,
      totalApprovedBudget: 1230000,
      capexPlanCurrentYear: 700000,
      opexPlanCurrentYear: 240000,
      capexActualYTD: 620000,
      opexActualYTD: 230000,
      capexActualToDate: 620000,
      opexActualToDate: 230000,
      actualsToDate: 850000,
      forecastAtCompletion: 1310000,
      variance: 80000,
      variancePercent: 6.5,
      budgetRAG: "Yellow",
      lastFinanceSync: "2026-09-01"
    },
    {
      projectId: 4,
      capexApprovedBudget: 1800000,
      opexApprovedBudget: 150000,
      totalApprovedBudget: 1950000,
      capexPlanCurrentYear: 500000,
      opexPlanCurrentYear: 50000,
      capexActualYTD: 410000,
      opexActualYTD: 35000,
      capexActualToDate: 410000,
      opexActualToDate: 35000,
      actualsToDate: 445000,
      forecastAtCompletion: 1950000,
      variance: 0,
      variancePercent: 0.0,
      budgetRAG: "Green",
      lastFinanceSync: "2026-09-01"
    },
    {
      projectId: 5,
      capexApprovedBudget: 750000,
      opexApprovedBudget: 180000,
      totalApprovedBudget: 930000,
      capexPlanCurrentYear: 600000,
      opexPlanCurrentYear: 150000,
      capexActualYTD: 520000,
      opexActualYTD: 140000,
      capexActualToDate: 520000,
      opexActualToDate: 140000,
      actualsToDate: 660000,
      forecastAtCompletion: 915000,
      variance: -15000,
      variancePercent: -1.61,
      budgetRAG: "Green",
      lastFinanceSync: "2026-09-01"
    }
  ],

  changeRequests: [
    {
      id: 701,
      projectId: 1,
      crNumber: "CR-001",
      title: "Add Disaster Recovery Multi-Region Replication for SQL Hyperscale",
      crDate: "2026-04-18",
      category: "Scope & Architecture",
      type: "Scope & Budget",
      costImpact: 45000,
      scheduleImpactWeeks: 1,
      status: "Approved",
      approvalStatus: "Approved",
      requestedDate: "2026-04-18",
      approvedBy: "Michael Chang (CIO)",
      justification: "Risk assessment mandated secondary geo-redundant standby in North Europe to comply with new regulatory resilience guidelines."
    },
    {
      id: 702,
      projectId: 2,
      crNumber: "CR-004",
      title: "Extend SAP Integration Specialist Retainer through Cutover",
      crDate: "2026-07-22",
      category: "Vendor & Budget",
      type: "Budget",
      costImpact: 120000,
      scheduleImpactWeeks: 2,
      status: "Approved",
      approvalStatus: "Approved",
      requestedDate: "2026-07-22",
      approvedBy: "Elena Rostova (CFO)",
      justification: "Critical EDI defects require tier-3 vendor engineers on site throughout UAT and hypercare."
    },
    {
      id: 703,
      projectId: 3,
      crNumber: "CR-008",
      title: "Biometric SDK Provider Swap & Compliance Rework",
      crDate: "2026-08-10",
      category: "Technical",
      type: "Schedule & Budget",
      costImpact: 65000,
      scheduleImpactWeeks: 4,
      status: "Pending Review",
      approvalStatus: "Under Review",
      requestedDate: "2026-08-10",
      approvedBy: "Pending Steering Committee",
      justification: "Removes third-party telemetry library to guarantee unconditional Apple and Google store clearance."
    }
  ],

  teamAllocations: [
    { id: 801, projectId: 1, personName: "Sarah Jenkins", role: "PM", ftePercent: 80, function: "Project Management" },
    { id: 802, projectId: 1, personName: "Alex Mercer", role: "Architect", ftePercent: 100, function: "Cloud Architecture" },
    { id: 803, projectId: 1, personName: "Devon Clark", role: "Developer", ftePercent: 100, function: "DevOps & Infrastructure" },
    { id: 804, projectId: 1, personName: "Priya Patel", role: "QA", ftePercent: 50, function: "Testing & Validation" },

    { id: 805, projectId: 2, personName: "David Vance", role: "PM", ftePercent: 100, function: "Project Management" },
    { id: 806, projectId: 2, personName: "Jens Moeller", role: "Architect", ftePercent: 100, function: "SAP Solution Architecture" },
    { id: 807, projectId: 2, personName: "Elena Garcia", role: "Developer", ftePercent: 100, function: "ABAP / Integration" },
    { id: 808, projectId: 2, personName: "Priya Patel", role: "QA", ftePercent: 50, function: "Testing & Validation" },

    { id: 809, projectId: 3, personName: "Amara Diallo", role: "PM", ftePercent: 80, function: "Project Management" },
    { id: 810, projectId: 3, personName: "Liam O'Connor", role: "Developer", ftePercent: 100, function: "iOS Development" },
    { id: 811, projectId: 3, personName: "Sophie Martin", role: "Designer", ftePercent: 60, function: "UI/UX Design" },
    { id: 812, projectId: 3, personName: "Kenji Sato", role: "QA", ftePercent: 100, function: "Mobile Automation QA" },

    { id: 813, projectId: 5, personName: "Rachel Wu", role: "PM", ftePercent: 100, function: "Cybersecurity PM" },
    { id: 814, projectId: 5, personName: "Alex Mercer", role: "Architect", ftePercent: 30, function: "Identity Architecture" },
    { id: 815, projectId: 5, personName: "Marcus Brody", role: "Developer", ftePercent: 100, function: "Entra ID & PowerShell" }
  ],

  monthlyStatus: [
    {
      id: 901,
      projectId: 1,
      reportingMonth: "August 2026",
      period: "August 2026",
      rag: "Green",
      summary: "Completed Tier 1 workloads migration. UAT for database tier approved with 0 Sev-1 issues.",
      achievements: "ExpressRoute gateway saturated at <35% latency; database cutover rehearsals succeeded without incident.",
      nextMonthPlan: "Prepare Phase Gate 2 review; kick off disaster recovery failover drill across North and West Europe.",
      nextSteps: "Prepare Phase Gate 2 review; kick off disaster recovery failover drill.",
      statusLocked: true,
      locked: true,
      submittedDate: "2026-08-31",
      reportedBy: "Sarah Jenkins"
    },
    {
      id: 902,
      projectId: 2,
      reportingMonth: "August 2026",
      period: "August 2026",
      rag: "Yellow",
      summary: "Integration testing continues. Budget variance flagged due to extended vendor specialist engagement.",
      achievements: "Data migration completed across all 14 distribution center schemas without data corruption.",
      nextMonthPlan: "Finalize EDI timeout patch with SAP core engineering; submit CR-004 budget adjustment.",
      nextSteps: "Finalize EDI timeout patch; submit CR-004 budget adjustment.",
      statusLocked: true,
      locked: true,
      submittedDate: "2026-08-31",
      reportedBy: "David Vance"
    },
    {
      id: 903,
      projectId: 3,
      reportingMonth: "August 2026",
      period: "August 2026",
      rag: "Red",
      summary: "Launch delayed due to store policy guideline rejection on biometric telemetry. New release build 3.0.4 compiled.",
      achievements: "Customer portal security penetration test passed with zero critical CVEs.",
      nextMonthPlan: "Resubmit to App Store review team; align customer communication strategy for October go-live.",
      nextSteps: "Resubmit to App Store review team; align customer communication strategy.",
      statusLocked: true,
      locked: true,
      submittedDate: "2026-08-31",
      reportedBy: "Amara Diallo"
    }
  ]
};
